// Code generated by ent, DO NOT EDIT.

package inboundtraffic

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inboundtraffic type in the database.
	Label = "inbound_traffic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldNodeUUID holds the string denoting the node_uuid field in the database.
	FieldNodeUUID = "node_uuid"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// FieldBytes holds the string denoting the bytes field in the database.
	FieldBytes = "bytes"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the inboundtraffic in the database.
	Table = "inbound_traffics"
)

// Columns holds all SQL columns for inboundtraffic fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldNodeUUID,
	FieldTag,
	FieldBytes,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBytes holds the default value on creation for the "bytes" field.
	DefaultBytes int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InboundTraffic queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByNodeUUID orders the results by the node_uuid field.
func ByNodeUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeUUID, opts...).ToFunc()
}

// ByTag orders the results by the tag field.
func ByTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTag, opts...).ToFunc()
}

// ByBytes orders the results by the bytes field.
func ByBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytes, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
