// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"time"
	"vpn-control/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCustomerID, v))
}

// TariffID applies equality check predicate on the "tariff_id" field. It's identical to TariffIDEQ.
func TariffID(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldTariffID, v))
}

// RwUserID applies equality check predicate on the "rw_user_id" field. It's identical to RwUserIDEQ.
func RwUserID(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRwUserID, v))
}

// PriceOverride applies equality check predicate on the "price_override" field. It's identical to PriceOverrideEQ.
func PriceOverride(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPriceOverride, v))
}

// AutoExtend applies equality check predicate on the "auto_extend" field. It's identical to AutoExtendEQ.
func AutoExtend(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldAutoExtend, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCustomerID, vs...))
}

// TariffIDEQ applies the EQ predicate on the "tariff_id" field.
func TariffIDEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldTariffID, v))
}

// TariffIDNEQ applies the NEQ predicate on the "tariff_id" field.
func TariffIDNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldTariffID, v))
}

// TariffIDIn applies the In predicate on the "tariff_id" field.
func TariffIDIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldTariffID, vs...))
}

// TariffIDNotIn applies the NotIn predicate on the "tariff_id" field.
func TariffIDNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldTariffID, vs...))
}

// TariffIDIsNil applies the IsNil predicate on the "tariff_id" field.
func TariffIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldTariffID))
}

// TariffIDNotNil applies the NotNil predicate on the "tariff_id" field.
func TariffIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldTariffID))
}

// RwUserIDEQ applies the EQ predicate on the "rw_user_id" field.
func RwUserIDEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRwUserID, v))
}

// RwUserIDNEQ applies the NEQ predicate on the "rw_user_id" field.
func RwUserIDNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRwUserID, v))
}

// RwUserIDIn applies the In predicate on the "rw_user_id" field.
func RwUserIDIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRwUserID, vs...))
}

// RwUserIDNotIn applies the NotIn predicate on the "rw_user_id" field.
func RwUserIDNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRwUserID, vs...))
}

// RwUserIDIsNil applies the IsNil predicate on the "rw_user_id" field.
func RwUserIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldRwUserID))
}

// RwUserIDNotNil applies the NotNil predicate on the "rw_user_id" field.
func RwUserIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldRwUserID))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldLabel, v))
}

// PriceOverrideEQ applies the EQ predicate on the "price_override" field.
func PriceOverrideEQ(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPriceOverride, v))
}

// PriceOverrideNEQ applies the NEQ predicate on the "price_override" field.
func PriceOverrideNEQ(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldPriceOverride, v))
}

// PriceOverrideIn applies the In predicate on the "price_override" field.
func PriceOverrideIn(vs ...int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldPriceOverride, vs...))
}

// PriceOverrideNotIn applies the NotIn predicate on the "price_override" field.
func PriceOverrideNotIn(vs ...int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldPriceOverride, vs...))
}

// PriceOverrideGT applies the GT predicate on the "price_override" field.
func PriceOverrideGT(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldPriceOverride, v))
}

// PriceOverrideGTE applies the GTE predicate on the "price_override" field.
func PriceOverrideGTE(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldPriceOverride, v))
}

// PriceOverrideLT applies the LT predicate on the "price_override" field.
func PriceOverrideLT(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldPriceOverride, v))
}

// PriceOverrideLTE applies the LTE predicate on the "price_override" field.
func PriceOverrideLTE(v int64) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldPriceOverride, v))
}

// PriceOverrideIsNil applies the IsNil predicate on the "price_override" field.
func PriceOverrideIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldPriceOverride))
}

// PriceOverrideNotNil applies the NotNil predicate on the "price_override" field.
func PriceOverrideNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldPriceOverride))
}

// AutoExtendEQ applies the EQ predicate on the "auto_extend" field.
func AutoExtendEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldAutoExtend, v))
}

// AutoExtendNEQ applies the NEQ predicate on the "auto_extend" field.
func AutoExtendNEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldAutoExtend, v))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTariff applies the HasEdge predicate on the "tariff" edge.
func HasTariff() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TariffTable, TariffColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTariffWith applies the HasEdge predicate on the "tariff" edge with a given conditions (other predicates).
func HasTariffWith(preds ...predicate.Tariff) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newTariffStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRwUser applies the HasEdge predicate on the "rw_user" edge.
func HasRwUser() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RwUserTable, RwUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRwUserWith applies the HasEdge predicate on the "rw_user" edge with a given conditions (other predicates).
func HasRwUserWith(preds ...predicate.RwUser) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newRwUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAddons applies the HasEdge predicate on the "addons" edge.
func HasAddons() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AddonsTable, AddonsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddonsWith applies the HasEdge predicate on the "addons" edge with a given conditions (other predicates).
func HasAddonsWith(preds ...predicate.SubscriptionAddon) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newAddonsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
