// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditlog type in the database.
	Label = "audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAt holds the string denoting the at field in the database.
	FieldAt = "at"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldEntity holds the string denoting the entity field in the database.
	FieldEntity = "entity"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldOk holds the string denoting the ok field in the database.
	FieldOk = "ok"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// Table holds the table name of the auditlog in the database.
	Table = "audit_logs"
)

// Columns holds all SQL columns for auditlog fields.
var Columns = []string{
	FieldID,
	FieldAt,
	FieldActor,
	FieldAction,
	FieldEntity,
	FieldEntityID,
	FieldPayload,
	FieldOk,
	FieldError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAt holds the default value on creation for the "at" field.
	DefaultAt func() time.Time
	// DefaultOk holds the default value on creation for the "ok" field.
	DefaultOk bool
)

// OrderOption defines the ordering options for the AuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAt orders the results by the at field.
func ByAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAt, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByEntity orders the results by the entity field.
func ByEntity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntity, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByOk orders the results by the ok field.
func ByOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOk, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}
