// Code generated by ent, DO NOT EDIT.

package addon

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the addon type in the database.
	Label = "addon"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrefix holds the string denoting the prefix field in the database.
	FieldPrefix = "prefix"
	// FieldSuffix holds the string denoting the suffix field in the database.
	FieldSuffix = "suffix"
	// FieldInConfig holds the string denoting the in_config field in the database.
	FieldInConfig = "in_config"
	// EdgeTariffs holds the string denoting the tariffs edge name in mutations.
	EdgeTariffs = "tariffs"
	// EdgeSubscriptionAddons holds the string denoting the subscription_addons edge name in mutations.
	EdgeSubscriptionAddons = "subscription_addons"
	// Table holds the table name of the addon in the database.
	Table = "addons"
	// TariffsTable is the table that holds the tariffs relation/edge.
	TariffsTable = "tariffs"
	// TariffsInverseTable is the table name for the Tariff entity.
	// It exists in this package in order to avoid circular dependency with the "tariff" package.
	TariffsInverseTable = "tariffs"
	// TariffsColumn is the table column denoting the tariffs relation/edge.
	TariffsColumn = "addon_id"
	// SubscriptionAddonsTable is the table that holds the subscription_addons relation/edge.
	SubscriptionAddonsTable = "subscription_addons"
	// SubscriptionAddonsInverseTable is the table name for the SubscriptionAddon entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionaddon" package.
	SubscriptionAddonsInverseTable = "subscription_addons"
	// SubscriptionAddonsColumn is the table column denoting the subscription_addons relation/edge.
	SubscriptionAddonsColumn = "addon_id"
)

// Columns holds all SQL columns for addon fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldPrefix,
	FieldSuffix,
	FieldInConfig,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultInConfig holds the default value on creation for the "in_config" field.
	DefaultInConfig bool
)

// OrderOption defines the ordering options for the Addon queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrefix orders the results by the prefix field.
func ByPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefix, opts...).ToFunc()
}

// BySuffix orders the results by the suffix field.
func BySuffix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuffix, opts...).ToFunc()
}

// ByInConfig orders the results by the in_config field.
func ByInConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInConfig, opts...).ToFunc()
}

// ByTariffsCount orders the results by tariffs count.
func ByTariffsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTariffsStep(), opts...)
	}
}

// ByTariffs orders the results by tariffs terms.
func ByTariffs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTariffsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubscriptionAddonsCount orders the results by subscription_addons count.
func BySubscriptionAddonsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubscriptionAddonsStep(), opts...)
	}
}

// BySubscriptionAddons orders the results by subscription_addons terms.
func BySubscriptionAddons(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionAddonsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTariffsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TariffsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TariffsTable, TariffsColumn),
	)
}
func newSubscriptionAddonsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionAddonsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionAddonsTable, SubscriptionAddonsColumn),
	)
}
