// Code generated by ent, DO NOT EDIT.

package expenseitem

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the expenseitem type in the database.
	Label = "expense_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldRwProviderUUID holds the string denoting the rw_provider_uuid field in the database.
	FieldRwProviderUUID = "rw_provider_uuid"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldPricing holds the string denoting the pricing field in the database.
	FieldPricing = "pricing"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldFeePercent holds the string denoting the fee_percent field in the database.
	FieldFeePercent = "fee_percent"
	// FieldSharePercent holds the string denoting the share_percent field in the database.
	FieldSharePercent = "share_percent"
	// FieldPricePerGB holds the string denoting the price_per_gb field in the database.
	FieldPricePerGB = "price_per_gb"
	// FieldMinCharge holds the string denoting the min_charge field in the database.
	FieldMinCharge = "min_charge"
	// FieldGBUnit holds the string denoting the gb_unit field in the database.
	FieldGBUnit = "gb_unit"
	// FieldMinMode holds the string denoting the min_mode field in the database.
	FieldMinMode = "min_mode"
	// FieldFreeGB holds the string denoting the free_gb field in the database.
	FieldFreeGB = "free_gb"
	// FieldTiers holds the string denoting the tiers field in the database.
	FieldTiers = "tiers"
	// FieldBillingDay holds the string denoting the billing_day field in the database.
	FieldBillingDay = "billing_day"
	// FieldRwNodeUUID holds the string denoting the rw_node_uuid field in the database.
	FieldRwNodeUUID = "rw_node_uuid"
	// FieldRwSquadUUID holds the string denoting the rw_squad_uuid field in the database.
	FieldRwSquadUUID = "rw_squad_uuid"
	// FieldNextDueDate holds the string denoting the next_due_date field in the database.
	FieldNextDueDate = "next_due_date"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// Table holds the table name of the expenseitem in the database.
	Table = "expense_items"
)

// Columns holds all SQL columns for expenseitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldProvider,
	FieldRwProviderUUID,
	FieldCurrency,
	FieldPricing,
	FieldAmount,
	FieldPeriod,
	FieldFeePercent,
	FieldSharePercent,
	FieldPricePerGB,
	FieldMinCharge,
	FieldGBUnit,
	FieldMinMode,
	FieldFreeGB,
	FieldTiers,
	FieldBillingDay,
	FieldRwNodeUUID,
	FieldRwSquadUUID,
	FieldNextDueDate,
	FieldActive,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount int64
	// DefaultFeePercent holds the default value on creation for the "fee_percent" field.
	DefaultFeePercent float64
	// DefaultSharePercent holds the default value on creation for the "share_percent" field.
	DefaultSharePercent float64
	// DefaultPricePerGB holds the default value on creation for the "price_per_gb" field.
	DefaultPricePerGB int64
	// DefaultMinCharge holds the default value on creation for the "min_charge" field.
	DefaultMinCharge int64
	// DefaultFreeGB holds the default value on creation for the "free_gb" field.
	DefaultFreeGB float64
	// DefaultBillingDay holds the default value on creation for the "billing_day" field.
	DefaultBillingDay int
	// BillingDayValidator is a validator for the "billing_day" field. It is called by the builders before save.
	BillingDayValidator func(int) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// Pricing defines the type for the "pricing" enum field.
type Pricing string

// PricingFixed is the default value of the Pricing enum.
const DefaultPricing = PricingFixed

// Pricing values.
const (
	PricingFixed   Pricing = "fixed"
	PricingMetered Pricing = "metered"
)

func (pr Pricing) String() string {
	return string(pr)
}

// PricingValidator is a validator for the "pricing" field enum values. It is called by the builders before save.
func PricingValidator(pr Pricing) error {
	switch pr {
	case PricingFixed, PricingMetered:
		return nil
	default:
		return fmt.Errorf("expenseitem: invalid enum value for pricing field: %q", pr)
	}
}

// Period defines the type for the "period" enum field.
type Period string

// PeriodMonth is the default value of the Period enum.
const DefaultPeriod = PeriodMonth

// Period values.
const (
	PeriodMonth Period = "month"
	PeriodYear  Period = "year"
)

func (pe Period) String() string {
	return string(pe)
}

// PeriodValidator is a validator for the "period" field enum values. It is called by the builders before save.
func PeriodValidator(pe Period) error {
	switch pe {
	case PeriodMonth, PeriodYear:
		return nil
	default:
		return fmt.Errorf("expenseitem: invalid enum value for period field: %q", pe)
	}
}

// GBUnit defines the type for the "gb_unit" enum field.
type GBUnit string

// GBUnitBinary is the default value of the GBUnit enum.
const DefaultGBUnit = GBUnitBinary

// GBUnit values.
const (
	GBUnitBinary  GBUnit = "binary"
	GBUnitDecimal GBUnit = "decimal"
)

func (gu GBUnit) String() string {
	return string(gu)
}

// GBUnitValidator is a validator for the "gb_unit" field enum values. It is called by the builders before save.
func GBUnitValidator(gu GBUnit) error {
	switch gu {
	case GBUnitBinary, GBUnitDecimal:
		return nil
	default:
		return fmt.Errorf("expenseitem: invalid enum value for gb_unit field: %q", gu)
	}
}

// MinMode defines the type for the "min_mode" enum field.
type MinMode string

// MinModeFloor is the default value of the MinMode enum.
const DefaultMinMode = MinModeFloor

// MinMode values.
const (
	MinModeFloor MinMode = "floor"
	MinModeFree  MinMode = "free"
)

func (mm MinMode) String() string {
	return string(mm)
}

// MinModeValidator is a validator for the "min_mode" field enum values. It is called by the builders before save.
func MinModeValidator(mm MinMode) error {
	switch mm {
	case MinModeFloor, MinModeFree:
		return nil
	default:
		return fmt.Errorf("expenseitem: invalid enum value for min_mode field: %q", mm)
	}
}

// OrderOption defines the ordering options for the ExpenseItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByRwProviderUUID orders the results by the rw_provider_uuid field.
func ByRwProviderUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRwProviderUUID, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByPricing orders the results by the pricing field.
func ByPricing(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricing, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}

// ByFeePercent orders the results by the fee_percent field.
func ByFeePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeePercent, opts...).ToFunc()
}

// BySharePercent orders the results by the share_percent field.
func BySharePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharePercent, opts...).ToFunc()
}

// ByPricePerGB orders the results by the price_per_gb field.
func ByPricePerGB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerGB, opts...).ToFunc()
}

// ByMinCharge orders the results by the min_charge field.
func ByMinCharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinCharge, opts...).ToFunc()
}

// ByGBUnit orders the results by the gb_unit field.
func ByGBUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGBUnit, opts...).ToFunc()
}

// ByMinMode orders the results by the min_mode field.
func ByMinMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinMode, opts...).ToFunc()
}

// ByFreeGB orders the results by the free_gb field.
func ByFreeGB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreeGB, opts...).ToFunc()
}

// ByBillingDay orders the results by the billing_day field.
func ByBillingDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingDay, opts...).ToFunc()
}

// ByRwNodeUUID orders the results by the rw_node_uuid field.
func ByRwNodeUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRwNodeUUID, opts...).ToFunc()
}

// ByRwSquadUUID orders the results by the rw_squad_uuid field.
func ByRwSquadUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRwSquadUUID, opts...).ToFunc()
}

// ByNextDueDate orders the results by the next_due_date field.
func ByNextDueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDueDate, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}
