// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/addon"
	"vpn-control/ent/subscriptionaddon"
	"vpn-control/ent/tariff"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddonCreate is the builder for creating a Addon entity.
type AddonCreate struct {
	config
	mutation *AddonMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AddonCreate) SetCreatedAt(v time.Time) *AddonCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AddonCreate) SetNillableCreatedAt(v *time.Time) *AddonCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AddonCreate) SetUpdatedAt(v time.Time) *AddonCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AddonCreate) SetNillableUpdatedAt(v *time.Time) *AddonCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AddonCreate) SetName(v string) *AddonCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *AddonCreate) SetPrefix(v string) *AddonCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_c *AddonCreate) SetNillablePrefix(v *string) *AddonCreate {
	if v != nil {
		_c.SetPrefix(*v)
	}
	return _c
}

// SetSuffix sets the "suffix" field.
func (_c *AddonCreate) SetSuffix(v string) *AddonCreate {
	_c.mutation.SetSuffix(v)
	return _c
}

// SetNillableSuffix sets the "suffix" field if the given value is not nil.
func (_c *AddonCreate) SetNillableSuffix(v *string) *AddonCreate {
	if v != nil {
		_c.SetSuffix(*v)
	}
	return _c
}

// SetInConfig sets the "in_config" field.
func (_c *AddonCreate) SetInConfig(v bool) *AddonCreate {
	_c.mutation.SetInConfig(v)
	return _c
}

// SetNillableInConfig sets the "in_config" field if the given value is not nil.
func (_c *AddonCreate) SetNillableInConfig(v *bool) *AddonCreate {
	if v != nil {
		_c.SetInConfig(*v)
	}
	return _c
}

// AddTariffIDs adds the "tariffs" edge to the Tariff entity by IDs.
func (_c *AddonCreate) AddTariffIDs(ids ...int) *AddonCreate {
	_c.mutation.AddTariffIDs(ids...)
	return _c
}

// AddTariffs adds the "tariffs" edges to the Tariff entity.
func (_c *AddonCreate) AddTariffs(v ...*Tariff) *AddonCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTariffIDs(ids...)
}

// AddSubscriptionAddonIDs adds the "subscription_addons" edge to the SubscriptionAddon entity by IDs.
func (_c *AddonCreate) AddSubscriptionAddonIDs(ids ...int) *AddonCreate {
	_c.mutation.AddSubscriptionAddonIDs(ids...)
	return _c
}

// AddSubscriptionAddons adds the "subscription_addons" edges to the SubscriptionAddon entity.
func (_c *AddonCreate) AddSubscriptionAddons(v ...*SubscriptionAddon) *AddonCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionAddonIDs(ids...)
}

// Mutation returns the AddonMutation object of the builder.
func (_c *AddonCreate) Mutation() *AddonMutation {
	return _c.mutation
}

// Save creates the Addon in the database.
func (_c *AddonCreate) Save(ctx context.Context) (*Addon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AddonCreate) SaveX(ctx context.Context) *Addon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AddonCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := addon.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := addon.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.InConfig(); !ok {
		v := addon.DefaultInConfig
		_c.mutation.SetInConfig(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AddonCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Addon.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Addon.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Addon.name"`)}
	}
	if _, ok := _c.mutation.InConfig(); !ok {
		return &ValidationError{Name: "in_config", err: errors.New(`ent: missing required field "Addon.in_config"`)}
	}
	return nil
}

func (_c *AddonCreate) sqlSave(ctx context.Context) (*Addon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AddonCreate) createSpec() (*Addon, *sqlgraph.CreateSpec) {
	var (
		_node = &Addon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(addon.Table, sqlgraph.NewFieldSpec(addon.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(addon.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(addon.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(addon.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(addon.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.Suffix(); ok {
		_spec.SetField(addon.FieldSuffix, field.TypeString, value)
		_node.Suffix = value
	}
	if value, ok := _c.mutation.InConfig(); ok {
		_spec.SetField(addon.FieldInConfig, field.TypeBool, value)
		_node.InConfig = value
	}
	if nodes := _c.mutation.TariffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   addon.TariffsTable,
			Columns: []string{addon.TariffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tariff.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionAddonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   addon.SubscriptionAddonsTable,
			Columns: []string{addon.SubscriptionAddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionaddon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Addon.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AddonUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AddonCreate) OnConflict(opts ...sql.ConflictOption) *AddonUpsertOne {
	_c.conflict = opts
	return &AddonUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Addon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AddonCreate) OnConflictColumns(columns ...string) *AddonUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AddonUpsertOne{
		create: _c,
	}
}

type (
	// AddonUpsertOne is the builder for "upsert"-ing
	//  one Addon node.
	AddonUpsertOne struct {
		create *AddonCreate
	}

	// AddonUpsert is the "OnConflict" setter.
	AddonUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AddonUpsert) SetUpdatedAt(v time.Time) *AddonUpsert {
	u.Set(addon.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AddonUpsert) UpdateUpdatedAt() *AddonUpsert {
	u.SetExcluded(addon.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AddonUpsert) SetName(v string) *AddonUpsert {
	u.Set(addon.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AddonUpsert) UpdateName() *AddonUpsert {
	u.SetExcluded(addon.FieldName)
	return u
}

// SetPrefix sets the "prefix" field.
func (u *AddonUpsert) SetPrefix(v string) *AddonUpsert {
	u.Set(addon.FieldPrefix, v)
	return u
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *AddonUpsert) UpdatePrefix() *AddonUpsert {
	u.SetExcluded(addon.FieldPrefix)
	return u
}

// ClearPrefix clears the value of the "prefix" field.
func (u *AddonUpsert) ClearPrefix() *AddonUpsert {
	u.SetNull(addon.FieldPrefix)
	return u
}

// SetSuffix sets the "suffix" field.
func (u *AddonUpsert) SetSuffix(v string) *AddonUpsert {
	u.Set(addon.FieldSuffix, v)
	return u
}

// UpdateSuffix sets the "suffix" field to the value that was provided on create.
func (u *AddonUpsert) UpdateSuffix() *AddonUpsert {
	u.SetExcluded(addon.FieldSuffix)
	return u
}

// ClearSuffix clears the value of the "suffix" field.
func (u *AddonUpsert) ClearSuffix() *AddonUpsert {
	u.SetNull(addon.FieldSuffix)
	return u
}

// SetInConfig sets the "in_config" field.
func (u *AddonUpsert) SetInConfig(v bool) *AddonUpsert {
	u.Set(addon.FieldInConfig, v)
	return u
}

// UpdateInConfig sets the "in_config" field to the value that was provided on create.
func (u *AddonUpsert) UpdateInConfig() *AddonUpsert {
	u.SetExcluded(addon.FieldInConfig)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Addon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AddonUpsertOne) UpdateNewValues() *AddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(addon.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Addon.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AddonUpsertOne) Ignore() *AddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AddonUpsertOne) DoNothing() *AddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AddonCreate.OnConflict
// documentation for more info.
func (u *AddonUpsertOne) Update(set func(*AddonUpsert)) *AddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AddonUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AddonUpsertOne) SetUpdatedAt(v time.Time) *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AddonUpsertOne) UpdateUpdatedAt() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AddonUpsertOne) SetName(v string) *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AddonUpsertOne) UpdateName() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateName()
	})
}

// SetPrefix sets the "prefix" field.
func (u *AddonUpsertOne) SetPrefix(v string) *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *AddonUpsertOne) UpdatePrefix() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.UpdatePrefix()
	})
}

// ClearPrefix clears the value of the "prefix" field.
func (u *AddonUpsertOne) ClearPrefix() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.ClearPrefix()
	})
}

// SetSuffix sets the "suffix" field.
func (u *AddonUpsertOne) SetSuffix(v string) *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.SetSuffix(v)
	})
}

// UpdateSuffix sets the "suffix" field to the value that was provided on create.
func (u *AddonUpsertOne) UpdateSuffix() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateSuffix()
	})
}

// ClearSuffix clears the value of the "suffix" field.
func (u *AddonUpsertOne) ClearSuffix() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.ClearSuffix()
	})
}

// SetInConfig sets the "in_config" field.
func (u *AddonUpsertOne) SetInConfig(v bool) *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.SetInConfig(v)
	})
}

// UpdateInConfig sets the "in_config" field to the value that was provided on create.
func (u *AddonUpsertOne) UpdateInConfig() *AddonUpsertOne {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateInConfig()
	})
}

// Exec executes the query.
func (u *AddonUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AddonCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AddonUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AddonUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AddonUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AddonCreateBulk is the builder for creating many Addon entities in bulk.
type AddonCreateBulk struct {
	config
	err      error
	builders []*AddonCreate
	conflict []sql.ConflictOption
}

// Save creates the Addon entities in the database.
func (_c *AddonCreateBulk) Save(ctx context.Context) ([]*Addon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Addon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AddonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AddonCreateBulk) SaveX(ctx context.Context) []*Addon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Addon.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AddonUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AddonCreateBulk) OnConflict(opts ...sql.ConflictOption) *AddonUpsertBulk {
	_c.conflict = opts
	return &AddonUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Addon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AddonCreateBulk) OnConflictColumns(columns ...string) *AddonUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AddonUpsertBulk{
		create: _c,
	}
}

// AddonUpsertBulk is the builder for "upsert"-ing
// a bulk of Addon nodes.
type AddonUpsertBulk struct {
	create *AddonCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Addon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AddonUpsertBulk) UpdateNewValues() *AddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(addon.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Addon.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AddonUpsertBulk) Ignore() *AddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AddonUpsertBulk) DoNothing() *AddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AddonCreateBulk.OnConflict
// documentation for more info.
func (u *AddonUpsertBulk) Update(set func(*AddonUpsert)) *AddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AddonUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AddonUpsertBulk) SetUpdatedAt(v time.Time) *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AddonUpsertBulk) UpdateUpdatedAt() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AddonUpsertBulk) SetName(v string) *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AddonUpsertBulk) UpdateName() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateName()
	})
}

// SetPrefix sets the "prefix" field.
func (u *AddonUpsertBulk) SetPrefix(v string) *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *AddonUpsertBulk) UpdatePrefix() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.UpdatePrefix()
	})
}

// ClearPrefix clears the value of the "prefix" field.
func (u *AddonUpsertBulk) ClearPrefix() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.ClearPrefix()
	})
}

// SetSuffix sets the "suffix" field.
func (u *AddonUpsertBulk) SetSuffix(v string) *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.SetSuffix(v)
	})
}

// UpdateSuffix sets the "suffix" field to the value that was provided on create.
func (u *AddonUpsertBulk) UpdateSuffix() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateSuffix()
	})
}

// ClearSuffix clears the value of the "suffix" field.
func (u *AddonUpsertBulk) ClearSuffix() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.ClearSuffix()
	})
}

// SetInConfig sets the "in_config" field.
func (u *AddonUpsertBulk) SetInConfig(v bool) *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.SetInConfig(v)
	})
}

// UpdateInConfig sets the "in_config" field to the value that was provided on create.
func (u *AddonUpsertBulk) UpdateInConfig() *AddonUpsertBulk {
	return u.Update(func(s *AddonUpsert) {
		s.UpdateInConfig()
	})
}

// Exec executes the query.
func (u *AddonUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AddonCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AddonCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AddonUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
