// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/apitoken"
	"vpn-control/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// APITokenUpdate is the builder for updating APIToken entities.
type APITokenUpdate struct {
	config
	hooks    []Hook
	mutation *APITokenMutation
}

// Where appends a list predicates to the APITokenUpdate builder.
func (_u *APITokenUpdate) Where(ps ...predicate.APIToken) *APITokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *APITokenUpdate) SetName(v string) *APITokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableName(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *APITokenUpdate) SetTokenHash(v string) *APITokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableTokenHash(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *APITokenUpdate) SetPrefix(v string) *APITokenUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillablePrefix(v *string) *APITokenUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *APITokenUpdate) SetScopes(v []string) *APITokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *APITokenUpdate) AppendScopes(v []string) *APITokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APITokenUpdate) SetLastUsedAt(v time.Time) *APITokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APITokenUpdate) SetNillableLastUsedAt(v *time.Time) *APITokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APITokenUpdate) ClearLastUsedAt() *APITokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// Mutation returns the APITokenMutation object of the builder.
func (_u *APITokenUpdate) Mutation() *APITokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APITokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APITokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APITokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APITokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APITokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *APITokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(apitoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apitoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apitoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apitoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APITokenUpdateOne is the builder for updating a single APIToken entity.
type APITokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APITokenMutation
}

// SetName sets the "name" field.
func (_u *APITokenUpdateOne) SetName(v string) *APITokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableName(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *APITokenUpdateOne) SetTokenHash(v string) *APITokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableTokenHash(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *APITokenUpdateOne) SetPrefix(v string) *APITokenUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillablePrefix(v *string) *APITokenUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *APITokenUpdateOne) SetScopes(v []string) *APITokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *APITokenUpdateOne) AppendScopes(v []string) *APITokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APITokenUpdateOne) SetLastUsedAt(v time.Time) *APITokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APITokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *APITokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APITokenUpdateOne) ClearLastUsedAt() *APITokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// Mutation returns the APITokenMutation object of the builder.
func (_u *APITokenUpdateOne) Mutation() *APITokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the APITokenUpdate builder.
func (_u *APITokenUpdateOne) Where(ps ...predicate.APIToken) *APITokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APITokenUpdateOne) Select(field string, fields ...string) *APITokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIToken entity.
func (_u *APITokenUpdateOne) Save(ctx context.Context) (*APIToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APITokenUpdateOne) SaveX(ctx context.Context) *APIToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APITokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APITokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APITokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *APITokenUpdateOne) sqlSave(ctx context.Context) (_node *APIToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apitoken.FieldID)
		for _, f := range fields {
			if !apitoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(apitoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apitoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(apitoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apitoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	_node = &APIToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
