// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"vpn-control/ent/expense"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Expense is the model entity for the Expense schema.
type Expense struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// RwProviderUUID holds the value of the "rw_provider_uuid" field.
	RwProviderUUID string `json:"rw_provider_uuid,omitempty"`
	// ExpenseItemID holds the value of the "expense_item_id" field.
	ExpenseItemID *int `json:"expense_item_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind expense.Kind `json:"kind,omitempty"`
	// OrigAmount holds the value of the "orig_amount" field.
	OrigAmount int64 `json:"orig_amount,omitempty"`
	// OrigCurrency holds the value of the "orig_currency" field.
	OrigCurrency string `json:"orig_currency,omitempty"`
	// FxRate holds the value of the "fx_rate" field.
	FxRate float64 `json:"fx_rate,omitempty"`
	// FeePercent holds the value of the "fee_percent" field.
	FeePercent float64 `json:"fee_percent,omitempty"`
	// SharePercent holds the value of the "share_percent" field.
	SharePercent float64 `json:"share_percent,omitempty"`
	// RubAmount holds the value of the "rub_amount" field.
	RubAmount int64 `json:"rub_amount,omitempty"`
	// RefundOfID holds the value of the "refund_of_id" field.
	RefundOfID *int `json:"refund_of_id,omitempty"`
	// CalcRubAmount holds the value of the "calc_rub_amount" field.
	CalcRubAmount *int64 `json:"calc_rub_amount,omitempty"`
	// MeteredGB holds the value of the "metered_gb" field.
	MeteredGB *float64 `json:"metered_gb,omitempty"`
	// Period holds the value of the "period" field.
	Period string `json:"period,omitempty"`
	// Note holds the value of the "note" field.
	Note         string `json:"note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Expense) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case expense.FieldFxRate, expense.FieldFeePercent, expense.FieldSharePercent, expense.FieldMeteredGB:
			values[i] = new(sql.NullFloat64)
		case expense.FieldID, expense.FieldExpenseItemID, expense.FieldOrigAmount, expense.FieldRubAmount, expense.FieldRefundOfID, expense.FieldCalcRubAmount:
			values[i] = new(sql.NullInt64)
		case expense.FieldProvider, expense.FieldRwProviderUUID, expense.FieldKind, expense.FieldOrigCurrency, expense.FieldPeriod, expense.FieldNote:
			values[i] = new(sql.NullString)
		case expense.FieldCreatedAt, expense.FieldUpdatedAt, expense.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Expense fields.
func (_m *Expense) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case expense.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case expense.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case expense.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case expense.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case expense.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case expense.FieldRwProviderUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rw_provider_uuid", values[i])
			} else if value.Valid {
				_m.RwProviderUUID = value.String
			}
		case expense.FieldExpenseItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expense_item_id", values[i])
			} else if value.Valid {
				_m.ExpenseItemID = new(int)
				*_m.ExpenseItemID = int(value.Int64)
			}
		case expense.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = expense.Kind(value.String)
			}
		case expense.FieldOrigAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field orig_amount", values[i])
			} else if value.Valid {
				_m.OrigAmount = value.Int64
			}
		case expense.FieldOrigCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field orig_currency", values[i])
			} else if value.Valid {
				_m.OrigCurrency = value.String
			}
		case expense.FieldFxRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fx_rate", values[i])
			} else if value.Valid {
				_m.FxRate = value.Float64
			}
		case expense.FieldFeePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_percent", values[i])
			} else if value.Valid {
				_m.FeePercent = value.Float64
			}
		case expense.FieldSharePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field share_percent", values[i])
			} else if value.Valid {
				_m.SharePercent = value.Float64
			}
		case expense.FieldRubAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rub_amount", values[i])
			} else if value.Valid {
				_m.RubAmount = value.Int64
			}
		case expense.FieldRefundOfID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_of_id", values[i])
			} else if value.Valid {
				_m.RefundOfID = new(int)
				*_m.RefundOfID = int(value.Int64)
			}
		case expense.FieldCalcRubAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field calc_rub_amount", values[i])
			} else if value.Valid {
				_m.CalcRubAmount = new(int64)
				*_m.CalcRubAmount = value.Int64
			}
		case expense.FieldMeteredGB:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field metered_gb", values[i])
			} else if value.Valid {
				_m.MeteredGB = new(float64)
				*_m.MeteredGB = value.Float64
			}
		case expense.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = value.String
			}
		case expense.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Expense.
// This includes values selected through modifiers, order, etc.
func (_m *Expense) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Expense.
// Note that you need to call Expense.Unwrap() before calling this method if this Expense
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Expense) Update() *ExpenseUpdateOne {
	return NewExpenseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Expense entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Expense) Unwrap() *Expense {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Expense is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Expense) String() string {
	var builder strings.Builder
	builder.WriteString("Expense(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("rw_provider_uuid=")
	builder.WriteString(_m.RwProviderUUID)
	builder.WriteString(", ")
	if v := _m.ExpenseItemID; v != nil {
		builder.WriteString("expense_item_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("orig_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrigAmount))
	builder.WriteString(", ")
	builder.WriteString("orig_currency=")
	builder.WriteString(_m.OrigCurrency)
	builder.WriteString(", ")
	builder.WriteString("fx_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.FxRate))
	builder.WriteString(", ")
	builder.WriteString("fee_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeePercent))
	builder.WriteString(", ")
	builder.WriteString("share_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharePercent))
	builder.WriteString(", ")
	builder.WriteString("rub_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RubAmount))
	builder.WriteString(", ")
	if v := _m.RefundOfID; v != nil {
		builder.WriteString("refund_of_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CalcRubAmount; v != nil {
		builder.WriteString("calc_rub_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MeteredGB; v != nil {
		builder.WriteString("metered_gb=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(_m.Period)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteByte(')')
	return builder.String()
}

// Expenses is a parsable slice of Expense.
type Expenses []*Expense
