// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/expense"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseCreate is the builder for creating a Expense entity.
type ExpenseCreate struct {
	config
	mutation *ExpenseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExpenseCreate) SetCreatedAt(v time.Time) *ExpenseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCreatedAt(v *time.Time) *ExpenseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExpenseCreate) SetUpdatedAt(v time.Time) *ExpenseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableUpdatedAt(v *time.Time) *ExpenseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDate sets the "date" field.
func (_c *ExpenseCreate) SetDate(v time.Time) *ExpenseCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ExpenseCreate) SetProvider(v string) *ExpenseCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableProvider(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetRwProviderUUID sets the "rw_provider_uuid" field.
func (_c *ExpenseCreate) SetRwProviderUUID(v string) *ExpenseCreate {
	_c.mutation.SetRwProviderUUID(v)
	return _c
}

// SetNillableRwProviderUUID sets the "rw_provider_uuid" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableRwProviderUUID(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetRwProviderUUID(*v)
	}
	return _c
}

// SetExpenseItemID sets the "expense_item_id" field.
func (_c *ExpenseCreate) SetExpenseItemID(v int) *ExpenseCreate {
	_c.mutation.SetExpenseItemID(v)
	return _c
}

// SetNillableExpenseItemID sets the "expense_item_id" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableExpenseItemID(v *int) *ExpenseCreate {
	if v != nil {
		_c.SetExpenseItemID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ExpenseCreate) SetKind(v expense.Kind) *ExpenseCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableKind(v *expense.Kind) *ExpenseCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetOrigAmount sets the "orig_amount" field.
func (_c *ExpenseCreate) SetOrigAmount(v int64) *ExpenseCreate {
	_c.mutation.SetOrigAmount(v)
	return _c
}

// SetOrigCurrency sets the "orig_currency" field.
func (_c *ExpenseCreate) SetOrigCurrency(v string) *ExpenseCreate {
	_c.mutation.SetOrigCurrency(v)
	return _c
}

// SetNillableOrigCurrency sets the "orig_currency" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableOrigCurrency(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetOrigCurrency(*v)
	}
	return _c
}

// SetFxRate sets the "fx_rate" field.
func (_c *ExpenseCreate) SetFxRate(v float64) *ExpenseCreate {
	_c.mutation.SetFxRate(v)
	return _c
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableFxRate(v *float64) *ExpenseCreate {
	if v != nil {
		_c.SetFxRate(*v)
	}
	return _c
}

// SetFeePercent sets the "fee_percent" field.
func (_c *ExpenseCreate) SetFeePercent(v float64) *ExpenseCreate {
	_c.mutation.SetFeePercent(v)
	return _c
}

// SetNillableFeePercent sets the "fee_percent" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableFeePercent(v *float64) *ExpenseCreate {
	if v != nil {
		_c.SetFeePercent(*v)
	}
	return _c
}

// SetSharePercent sets the "share_percent" field.
func (_c *ExpenseCreate) SetSharePercent(v float64) *ExpenseCreate {
	_c.mutation.SetSharePercent(v)
	return _c
}

// SetNillableSharePercent sets the "share_percent" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableSharePercent(v *float64) *ExpenseCreate {
	if v != nil {
		_c.SetSharePercent(*v)
	}
	return _c
}

// SetRubAmount sets the "rub_amount" field.
func (_c *ExpenseCreate) SetRubAmount(v int64) *ExpenseCreate {
	_c.mutation.SetRubAmount(v)
	return _c
}

// SetRefundOfID sets the "refund_of_id" field.
func (_c *ExpenseCreate) SetRefundOfID(v int) *ExpenseCreate {
	_c.mutation.SetRefundOfID(v)
	return _c
}

// SetNillableRefundOfID sets the "refund_of_id" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableRefundOfID(v *int) *ExpenseCreate {
	if v != nil {
		_c.SetRefundOfID(*v)
	}
	return _c
}

// SetCalcRubAmount sets the "calc_rub_amount" field.
func (_c *ExpenseCreate) SetCalcRubAmount(v int64) *ExpenseCreate {
	_c.mutation.SetCalcRubAmount(v)
	return _c
}

// SetNillableCalcRubAmount sets the "calc_rub_amount" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCalcRubAmount(v *int64) *ExpenseCreate {
	if v != nil {
		_c.SetCalcRubAmount(*v)
	}
	return _c
}

// SetMeteredGB sets the "metered_gb" field.
func (_c *ExpenseCreate) SetMeteredGB(v float64) *ExpenseCreate {
	_c.mutation.SetMeteredGB(v)
	return _c
}

// SetNillableMeteredGB sets the "metered_gb" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableMeteredGB(v *float64) *ExpenseCreate {
	if v != nil {
		_c.SetMeteredGB(*v)
	}
	return _c
}

// SetPeriod sets the "period" field.
func (_c *ExpenseCreate) SetPeriod(v string) *ExpenseCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillablePeriod(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetPeriod(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ExpenseCreate) SetNote(v string) *ExpenseCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableNote(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// Mutation returns the ExpenseMutation object of the builder.
func (_c *ExpenseCreate) Mutation() *ExpenseMutation {
	return _c.mutation
}

// Save creates the Expense in the database.
func (_c *ExpenseCreate) Save(ctx context.Context) (*Expense, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpenseCreate) SaveX(ctx context.Context) *Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpenseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := expense.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := expense.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := expense.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.OrigCurrency(); !ok {
		v := expense.DefaultOrigCurrency
		_c.mutation.SetOrigCurrency(v)
	}
	if _, ok := _c.mutation.FxRate(); !ok {
		v := expense.DefaultFxRate
		_c.mutation.SetFxRate(v)
	}
	if _, ok := _c.mutation.FeePercent(); !ok {
		v := expense.DefaultFeePercent
		_c.mutation.SetFeePercent(v)
	}
	if _, ok := _c.mutation.SharePercent(); !ok {
		v := expense.DefaultSharePercent
		_c.mutation.SetSharePercent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpenseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Expense.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Expense.updated_at"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Expense.date"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Expense.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := expense.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Expense.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrigAmount(); !ok {
		return &ValidationError{Name: "orig_amount", err: errors.New(`ent: missing required field "Expense.orig_amount"`)}
	}
	if v, ok := _c.mutation.OrigAmount(); ok {
		if err := expense.OrigAmountValidator(v); err != nil {
			return &ValidationError{Name: "orig_amount", err: fmt.Errorf(`ent: validator failed for field "Expense.orig_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrigCurrency(); !ok {
		return &ValidationError{Name: "orig_currency", err: errors.New(`ent: missing required field "Expense.orig_currency"`)}
	}
	if _, ok := _c.mutation.FxRate(); !ok {
		return &ValidationError{Name: "fx_rate", err: errors.New(`ent: missing required field "Expense.fx_rate"`)}
	}
	if _, ok := _c.mutation.FeePercent(); !ok {
		return &ValidationError{Name: "fee_percent", err: errors.New(`ent: missing required field "Expense.fee_percent"`)}
	}
	if _, ok := _c.mutation.SharePercent(); !ok {
		return &ValidationError{Name: "share_percent", err: errors.New(`ent: missing required field "Expense.share_percent"`)}
	}
	if _, ok := _c.mutation.RubAmount(); !ok {
		return &ValidationError{Name: "rub_amount", err: errors.New(`ent: missing required field "Expense.rub_amount"`)}
	}
	return nil
}

func (_c *ExpenseCreate) sqlSave(ctx context.Context) (*Expense, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpenseCreate) createSpec() (*Expense, *sqlgraph.CreateSpec) {
	var (
		_node = &Expense{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expense.Table, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(expense.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(expense.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(expense.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(expense.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.RwProviderUUID(); ok {
		_spec.SetField(expense.FieldRwProviderUUID, field.TypeString, value)
		_node.RwProviderUUID = value
	}
	if value, ok := _c.mutation.ExpenseItemID(); ok {
		_spec.SetField(expense.FieldExpenseItemID, field.TypeInt, value)
		_node.ExpenseItemID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(expense.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.OrigAmount(); ok {
		_spec.SetField(expense.FieldOrigAmount, field.TypeInt64, value)
		_node.OrigAmount = value
	}
	if value, ok := _c.mutation.OrigCurrency(); ok {
		_spec.SetField(expense.FieldOrigCurrency, field.TypeString, value)
		_node.OrigCurrency = value
	}
	if value, ok := _c.mutation.FxRate(); ok {
		_spec.SetField(expense.FieldFxRate, field.TypeFloat64, value)
		_node.FxRate = value
	}
	if value, ok := _c.mutation.FeePercent(); ok {
		_spec.SetField(expense.FieldFeePercent, field.TypeFloat64, value)
		_node.FeePercent = value
	}
	if value, ok := _c.mutation.SharePercent(); ok {
		_spec.SetField(expense.FieldSharePercent, field.TypeFloat64, value)
		_node.SharePercent = value
	}
	if value, ok := _c.mutation.RubAmount(); ok {
		_spec.SetField(expense.FieldRubAmount, field.TypeInt64, value)
		_node.RubAmount = value
	}
	if value, ok := _c.mutation.RefundOfID(); ok {
		_spec.SetField(expense.FieldRefundOfID, field.TypeInt, value)
		_node.RefundOfID = &value
	}
	if value, ok := _c.mutation.CalcRubAmount(); ok {
		_spec.SetField(expense.FieldCalcRubAmount, field.TypeInt64, value)
		_node.CalcRubAmount = &value
	}
	if value, ok := _c.mutation.MeteredGB(); ok {
		_spec.SetField(expense.FieldMeteredGB, field.TypeFloat64, value)
		_node.MeteredGB = &value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(expense.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(expense.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Expense.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpenseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpenseCreate) OnConflict(opts ...sql.ConflictOption) *ExpenseUpsertOne {
	_c.conflict = opts
	return &ExpenseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Expense.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpenseCreate) OnConflictColumns(columns ...string) *ExpenseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpenseUpsertOne{
		create: _c,
	}
}

type (
	// ExpenseUpsertOne is the builder for "upsert"-ing
	//  one Expense node.
	ExpenseUpsertOne struct {
		create *ExpenseCreate
	}

	// ExpenseUpsert is the "OnConflict" setter.
	ExpenseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseUpsert) SetUpdatedAt(v time.Time) *ExpenseUpsert {
	u.Set(expense.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateUpdatedAt() *ExpenseUpsert {
	u.SetExcluded(expense.FieldUpdatedAt)
	return u
}

// SetDate sets the "date" field.
func (u *ExpenseUpsert) SetDate(v time.Time) *ExpenseUpsert {
	u.Set(expense.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateDate() *ExpenseUpsert {
	u.SetExcluded(expense.FieldDate)
	return u
}

// SetProvider sets the "provider" field.
func (u *ExpenseUpsert) SetProvider(v string) *ExpenseUpsert {
	u.Set(expense.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateProvider() *ExpenseUpsert {
	u.SetExcluded(expense.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *ExpenseUpsert) ClearProvider() *ExpenseUpsert {
	u.SetNull(expense.FieldProvider)
	return u
}

// SetRwProviderUUID sets the "rw_provider_uuid" field.
func (u *ExpenseUpsert) SetRwProviderUUID(v string) *ExpenseUpsert {
	u.Set(expense.FieldRwProviderUUID, v)
	return u
}

// UpdateRwProviderUUID sets the "rw_provider_uuid" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateRwProviderUUID() *ExpenseUpsert {
	u.SetExcluded(expense.FieldRwProviderUUID)
	return u
}

// ClearRwProviderUUID clears the value of the "rw_provider_uuid" field.
func (u *ExpenseUpsert) ClearRwProviderUUID() *ExpenseUpsert {
	u.SetNull(expense.FieldRwProviderUUID)
	return u
}

// SetExpenseItemID sets the "expense_item_id" field.
func (u *ExpenseUpsert) SetExpenseItemID(v int) *ExpenseUpsert {
	u.Set(expense.FieldExpenseItemID, v)
	return u
}

// UpdateExpenseItemID sets the "expense_item_id" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateExpenseItemID() *ExpenseUpsert {
	u.SetExcluded(expense.FieldExpenseItemID)
	return u
}

// AddExpenseItemID adds v to the "expense_item_id" field.
func (u *ExpenseUpsert) AddExpenseItemID(v int) *ExpenseUpsert {
	u.Add(expense.FieldExpenseItemID, v)
	return u
}

// ClearExpenseItemID clears the value of the "expense_item_id" field.
func (u *ExpenseUpsert) ClearExpenseItemID() *ExpenseUpsert {
	u.SetNull(expense.FieldExpenseItemID)
	return u
}

// SetKind sets the "kind" field.
func (u *ExpenseUpsert) SetKind(v expense.Kind) *ExpenseUpsert {
	u.Set(expense.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateKind() *ExpenseUpsert {
	u.SetExcluded(expense.FieldKind)
	return u
}

// SetOrigAmount sets the "orig_amount" field.
func (u *ExpenseUpsert) SetOrigAmount(v int64) *ExpenseUpsert {
	u.Set(expense.FieldOrigAmount, v)
	return u
}

// UpdateOrigAmount sets the "orig_amount" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateOrigAmount() *ExpenseUpsert {
	u.SetExcluded(expense.FieldOrigAmount)
	return u
}

// AddOrigAmount adds v to the "orig_amount" field.
func (u *ExpenseUpsert) AddOrigAmount(v int64) *ExpenseUpsert {
	u.Add(expense.FieldOrigAmount, v)
	return u
}

// SetOrigCurrency sets the "orig_currency" field.
func (u *ExpenseUpsert) SetOrigCurrency(v string) *ExpenseUpsert {
	u.Set(expense.FieldOrigCurrency, v)
	return u
}

// UpdateOrigCurrency sets the "orig_currency" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateOrigCurrency() *ExpenseUpsert {
	u.SetExcluded(expense.FieldOrigCurrency)
	return u
}

// SetFxRate sets the "fx_rate" field.
func (u *ExpenseUpsert) SetFxRate(v float64) *ExpenseUpsert {
	u.Set(expense.FieldFxRate, v)
	return u
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateFxRate() *ExpenseUpsert {
	u.SetExcluded(expense.FieldFxRate)
	return u
}

// AddFxRate adds v to the "fx_rate" field.
func (u *ExpenseUpsert) AddFxRate(v float64) *ExpenseUpsert {
	u.Add(expense.FieldFxRate, v)
	return u
}

// SetFeePercent sets the "fee_percent" field.
func (u *ExpenseUpsert) SetFeePercent(v float64) *ExpenseUpsert {
	u.Set(expense.FieldFeePercent, v)
	return u
}

// UpdateFeePercent sets the "fee_percent" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateFeePercent() *ExpenseUpsert {
	u.SetExcluded(expense.FieldFeePercent)
	return u
}

// AddFeePercent adds v to the "fee_percent" field.
func (u *ExpenseUpsert) AddFeePercent(v float64) *ExpenseUpsert {
	u.Add(expense.FieldFeePercent, v)
	return u
}

// SetSharePercent sets the "share_percent" field.
func (u *ExpenseUpsert) SetSharePercent(v float64) *ExpenseUpsert {
	u.Set(expense.FieldSharePercent, v)
	return u
}

// UpdateSharePercent sets the "share_percent" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateSharePercent() *ExpenseUpsert {
	u.SetExcluded(expense.FieldSharePercent)
	return u
}

// AddSharePercent adds v to the "share_percent" field.
func (u *ExpenseUpsert) AddSharePercent(v float64) *ExpenseUpsert {
	u.Add(expense.FieldSharePercent, v)
	return u
}

// SetRubAmount sets the "rub_amount" field.
func (u *ExpenseUpsert) SetRubAmount(v int64) *ExpenseUpsert {
	u.Set(expense.FieldRubAmount, v)
	return u
}

// UpdateRubAmount sets the "rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateRubAmount() *ExpenseUpsert {
	u.SetExcluded(expense.FieldRubAmount)
	return u
}

// AddRubAmount adds v to the "rub_amount" field.
func (u *ExpenseUpsert) AddRubAmount(v int64) *ExpenseUpsert {
	u.Add(expense.FieldRubAmount, v)
	return u
}

// SetRefundOfID sets the "refund_of_id" field.
func (u *ExpenseUpsert) SetRefundOfID(v int) *ExpenseUpsert {
	u.Set(expense.FieldRefundOfID, v)
	return u
}

// UpdateRefundOfID sets the "refund_of_id" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateRefundOfID() *ExpenseUpsert {
	u.SetExcluded(expense.FieldRefundOfID)
	return u
}

// AddRefundOfID adds v to the "refund_of_id" field.
func (u *ExpenseUpsert) AddRefundOfID(v int) *ExpenseUpsert {
	u.Add(expense.FieldRefundOfID, v)
	return u
}

// ClearRefundOfID clears the value of the "refund_of_id" field.
func (u *ExpenseUpsert) ClearRefundOfID() *ExpenseUpsert {
	u.SetNull(expense.FieldRefundOfID)
	return u
}

// SetCalcRubAmount sets the "calc_rub_amount" field.
func (u *ExpenseUpsert) SetCalcRubAmount(v int64) *ExpenseUpsert {
	u.Set(expense.FieldCalcRubAmount, v)
	return u
}

// UpdateCalcRubAmount sets the "calc_rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateCalcRubAmount() *ExpenseUpsert {
	u.SetExcluded(expense.FieldCalcRubAmount)
	return u
}

// AddCalcRubAmount adds v to the "calc_rub_amount" field.
func (u *ExpenseUpsert) AddCalcRubAmount(v int64) *ExpenseUpsert {
	u.Add(expense.FieldCalcRubAmount, v)
	return u
}

// ClearCalcRubAmount clears the value of the "calc_rub_amount" field.
func (u *ExpenseUpsert) ClearCalcRubAmount() *ExpenseUpsert {
	u.SetNull(expense.FieldCalcRubAmount)
	return u
}

// SetMeteredGB sets the "metered_gb" field.
func (u *ExpenseUpsert) SetMeteredGB(v float64) *ExpenseUpsert {
	u.Set(expense.FieldMeteredGB, v)
	return u
}

// UpdateMeteredGB sets the "metered_gb" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateMeteredGB() *ExpenseUpsert {
	u.SetExcluded(expense.FieldMeteredGB)
	return u
}

// AddMeteredGB adds v to the "metered_gb" field.
func (u *ExpenseUpsert) AddMeteredGB(v float64) *ExpenseUpsert {
	u.Add(expense.FieldMeteredGB, v)
	return u
}

// ClearMeteredGB clears the value of the "metered_gb" field.
func (u *ExpenseUpsert) ClearMeteredGB() *ExpenseUpsert {
	u.SetNull(expense.FieldMeteredGB)
	return u
}

// SetPeriod sets the "period" field.
func (u *ExpenseUpsert) SetPeriod(v string) *ExpenseUpsert {
	u.Set(expense.FieldPeriod, v)
	return u
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdatePeriod() *ExpenseUpsert {
	u.SetExcluded(expense.FieldPeriod)
	return u
}

// ClearPeriod clears the value of the "period" field.
func (u *ExpenseUpsert) ClearPeriod() *ExpenseUpsert {
	u.SetNull(expense.FieldPeriod)
	return u
}

// SetNote sets the "note" field.
func (u *ExpenseUpsert) SetNote(v string) *ExpenseUpsert {
	u.Set(expense.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ExpenseUpsert) UpdateNote() *ExpenseUpsert {
	u.SetExcluded(expense.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *ExpenseUpsert) ClearNote() *ExpenseUpsert {
	u.SetNull(expense.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Expense.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExpenseUpsertOne) UpdateNewValues() *ExpenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(expense.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Expense.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExpenseUpsertOne) Ignore() *ExpenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpenseUpsertOne) DoNothing() *ExpenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpenseCreate.OnConflict
// documentation for more info.
func (u *ExpenseUpsertOne) Update(set func(*ExpenseUpsert)) *ExpenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpenseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseUpsertOne) SetUpdatedAt(v time.Time) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateUpdatedAt() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDate sets the "date" field.
func (u *ExpenseUpsertOne) SetDate(v time.Time) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateDate() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateDate()
	})
}

// SetProvider sets the "provider" field.
func (u *ExpenseUpsertOne) SetProvider(v string) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateProvider() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *ExpenseUpsertOne) ClearProvider() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearProvider()
	})
}

// SetRwProviderUUID sets the "rw_provider_uuid" field.
func (u *ExpenseUpsertOne) SetRwProviderUUID(v string) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRwProviderUUID(v)
	})
}

// UpdateRwProviderUUID sets the "rw_provider_uuid" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateRwProviderUUID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRwProviderUUID()
	})
}

// ClearRwProviderUUID clears the value of the "rw_provider_uuid" field.
func (u *ExpenseUpsertOne) ClearRwProviderUUID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearRwProviderUUID()
	})
}

// SetExpenseItemID sets the "expense_item_id" field.
func (u *ExpenseUpsertOne) SetExpenseItemID(v int) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetExpenseItemID(v)
	})
}

// AddExpenseItemID adds v to the "expense_item_id" field.
func (u *ExpenseUpsertOne) AddExpenseItemID(v int) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddExpenseItemID(v)
	})
}

// UpdateExpenseItemID sets the "expense_item_id" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateExpenseItemID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateExpenseItemID()
	})
}

// ClearExpenseItemID clears the value of the "expense_item_id" field.
func (u *ExpenseUpsertOne) ClearExpenseItemID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearExpenseItemID()
	})
}

// SetKind sets the "kind" field.
func (u *ExpenseUpsertOne) SetKind(v expense.Kind) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateKind() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateKind()
	})
}

// SetOrigAmount sets the "orig_amount" field.
func (u *ExpenseUpsertOne) SetOrigAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetOrigAmount(v)
	})
}

// AddOrigAmount adds v to the "orig_amount" field.
func (u *ExpenseUpsertOne) AddOrigAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddOrigAmount(v)
	})
}

// UpdateOrigAmount sets the "orig_amount" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateOrigAmount() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateOrigAmount()
	})
}

// SetOrigCurrency sets the "orig_currency" field.
func (u *ExpenseUpsertOne) SetOrigCurrency(v string) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetOrigCurrency(v)
	})
}

// UpdateOrigCurrency sets the "orig_currency" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateOrigCurrency() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateOrigCurrency()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *ExpenseUpsertOne) SetFxRate(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetFxRate(v)
	})
}

// AddFxRate adds v to the "fx_rate" field.
func (u *ExpenseUpsertOne) AddFxRate(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateFxRate() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateFxRate()
	})
}

// SetFeePercent sets the "fee_percent" field.
func (u *ExpenseUpsertOne) SetFeePercent(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetFeePercent(v)
	})
}

// AddFeePercent adds v to the "fee_percent" field.
func (u *ExpenseUpsertOne) AddFeePercent(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddFeePercent(v)
	})
}

// UpdateFeePercent sets the "fee_percent" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateFeePercent() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateFeePercent()
	})
}

// SetSharePercent sets the "share_percent" field.
func (u *ExpenseUpsertOne) SetSharePercent(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetSharePercent(v)
	})
}

// AddSharePercent adds v to the "share_percent" field.
func (u *ExpenseUpsertOne) AddSharePercent(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddSharePercent(v)
	})
}

// UpdateSharePercent sets the "share_percent" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateSharePercent() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateSharePercent()
	})
}

// SetRubAmount sets the "rub_amount" field.
func (u *ExpenseUpsertOne) SetRubAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRubAmount(v)
	})
}

// AddRubAmount adds v to the "rub_amount" field.
func (u *ExpenseUpsertOne) AddRubAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddRubAmount(v)
	})
}

// UpdateRubAmount sets the "rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateRubAmount() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRubAmount()
	})
}

// SetRefundOfID sets the "refund_of_id" field.
func (u *ExpenseUpsertOne) SetRefundOfID(v int) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRefundOfID(v)
	})
}

// AddRefundOfID adds v to the "refund_of_id" field.
func (u *ExpenseUpsertOne) AddRefundOfID(v int) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddRefundOfID(v)
	})
}

// UpdateRefundOfID sets the "refund_of_id" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateRefundOfID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRefundOfID()
	})
}

// ClearRefundOfID clears the value of the "refund_of_id" field.
func (u *ExpenseUpsertOne) ClearRefundOfID() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearRefundOfID()
	})
}

// SetCalcRubAmount sets the "calc_rub_amount" field.
func (u *ExpenseUpsertOne) SetCalcRubAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetCalcRubAmount(v)
	})
}

// AddCalcRubAmount adds v to the "calc_rub_amount" field.
func (u *ExpenseUpsertOne) AddCalcRubAmount(v int64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddCalcRubAmount(v)
	})
}

// UpdateCalcRubAmount sets the "calc_rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateCalcRubAmount() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateCalcRubAmount()
	})
}

// ClearCalcRubAmount clears the value of the "calc_rub_amount" field.
func (u *ExpenseUpsertOne) ClearCalcRubAmount() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearCalcRubAmount()
	})
}

// SetMeteredGB sets the "metered_gb" field.
func (u *ExpenseUpsertOne) SetMeteredGB(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetMeteredGB(v)
	})
}

// AddMeteredGB adds v to the "metered_gb" field.
func (u *ExpenseUpsertOne) AddMeteredGB(v float64) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddMeteredGB(v)
	})
}

// UpdateMeteredGB sets the "metered_gb" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateMeteredGB() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateMeteredGB()
	})
}

// ClearMeteredGB clears the value of the "metered_gb" field.
func (u *ExpenseUpsertOne) ClearMeteredGB() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearMeteredGB()
	})
}

// SetPeriod sets the "period" field.
func (u *ExpenseUpsertOne) SetPeriod(v string) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdatePeriod() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdatePeriod()
	})
}

// ClearPeriod clears the value of the "period" field.
func (u *ExpenseUpsertOne) ClearPeriod() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearPeriod()
	})
}

// SetNote sets the "note" field.
func (u *ExpenseUpsertOne) SetNote(v string) *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ExpenseUpsertOne) UpdateNote() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ExpenseUpsertOne) ClearNote() *ExpenseUpsertOne {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *ExpenseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExpenseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpenseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExpenseUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExpenseUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExpenseCreateBulk is the builder for creating many Expense entities in bulk.
type ExpenseCreateBulk struct {
	config
	err      error
	builders []*ExpenseCreate
	conflict []sql.ConflictOption
}

// Save creates the Expense entities in the database.
func (_c *ExpenseCreateBulk) Save(ctx context.Context) ([]*Expense, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Expense, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpenseCreateBulk) SaveX(ctx context.Context) []*Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Expense.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpenseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpenseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExpenseUpsertBulk {
	_c.conflict = opts
	return &ExpenseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Expense.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpenseCreateBulk) OnConflictColumns(columns ...string) *ExpenseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpenseUpsertBulk{
		create: _c,
	}
}

// ExpenseUpsertBulk is the builder for "upsert"-ing
// a bulk of Expense nodes.
type ExpenseUpsertBulk struct {
	create *ExpenseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Expense.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExpenseUpsertBulk) UpdateNewValues() *ExpenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(expense.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Expense.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExpenseUpsertBulk) Ignore() *ExpenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpenseUpsertBulk) DoNothing() *ExpenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpenseCreateBulk.OnConflict
// documentation for more info.
func (u *ExpenseUpsertBulk) Update(set func(*ExpenseUpsert)) *ExpenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpenseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseUpsertBulk) SetUpdatedAt(v time.Time) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateUpdatedAt() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDate sets the "date" field.
func (u *ExpenseUpsertBulk) SetDate(v time.Time) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateDate() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateDate()
	})
}

// SetProvider sets the "provider" field.
func (u *ExpenseUpsertBulk) SetProvider(v string) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateProvider() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *ExpenseUpsertBulk) ClearProvider() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearProvider()
	})
}

// SetRwProviderUUID sets the "rw_provider_uuid" field.
func (u *ExpenseUpsertBulk) SetRwProviderUUID(v string) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRwProviderUUID(v)
	})
}

// UpdateRwProviderUUID sets the "rw_provider_uuid" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateRwProviderUUID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRwProviderUUID()
	})
}

// ClearRwProviderUUID clears the value of the "rw_provider_uuid" field.
func (u *ExpenseUpsertBulk) ClearRwProviderUUID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearRwProviderUUID()
	})
}

// SetExpenseItemID sets the "expense_item_id" field.
func (u *ExpenseUpsertBulk) SetExpenseItemID(v int) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetExpenseItemID(v)
	})
}

// AddExpenseItemID adds v to the "expense_item_id" field.
func (u *ExpenseUpsertBulk) AddExpenseItemID(v int) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddExpenseItemID(v)
	})
}

// UpdateExpenseItemID sets the "expense_item_id" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateExpenseItemID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateExpenseItemID()
	})
}

// ClearExpenseItemID clears the value of the "expense_item_id" field.
func (u *ExpenseUpsertBulk) ClearExpenseItemID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearExpenseItemID()
	})
}

// SetKind sets the "kind" field.
func (u *ExpenseUpsertBulk) SetKind(v expense.Kind) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateKind() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateKind()
	})
}

// SetOrigAmount sets the "orig_amount" field.
func (u *ExpenseUpsertBulk) SetOrigAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetOrigAmount(v)
	})
}

// AddOrigAmount adds v to the "orig_amount" field.
func (u *ExpenseUpsertBulk) AddOrigAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddOrigAmount(v)
	})
}

// UpdateOrigAmount sets the "orig_amount" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateOrigAmount() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateOrigAmount()
	})
}

// SetOrigCurrency sets the "orig_currency" field.
func (u *ExpenseUpsertBulk) SetOrigCurrency(v string) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetOrigCurrency(v)
	})
}

// UpdateOrigCurrency sets the "orig_currency" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateOrigCurrency() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateOrigCurrency()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *ExpenseUpsertBulk) SetFxRate(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetFxRate(v)
	})
}

// AddFxRate adds v to the "fx_rate" field.
func (u *ExpenseUpsertBulk) AddFxRate(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateFxRate() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateFxRate()
	})
}

// SetFeePercent sets the "fee_percent" field.
func (u *ExpenseUpsertBulk) SetFeePercent(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetFeePercent(v)
	})
}

// AddFeePercent adds v to the "fee_percent" field.
func (u *ExpenseUpsertBulk) AddFeePercent(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddFeePercent(v)
	})
}

// UpdateFeePercent sets the "fee_percent" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateFeePercent() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateFeePercent()
	})
}

// SetSharePercent sets the "share_percent" field.
func (u *ExpenseUpsertBulk) SetSharePercent(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetSharePercent(v)
	})
}

// AddSharePercent adds v to the "share_percent" field.
func (u *ExpenseUpsertBulk) AddSharePercent(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddSharePercent(v)
	})
}

// UpdateSharePercent sets the "share_percent" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateSharePercent() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateSharePercent()
	})
}

// SetRubAmount sets the "rub_amount" field.
func (u *ExpenseUpsertBulk) SetRubAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRubAmount(v)
	})
}

// AddRubAmount adds v to the "rub_amount" field.
func (u *ExpenseUpsertBulk) AddRubAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddRubAmount(v)
	})
}

// UpdateRubAmount sets the "rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateRubAmount() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRubAmount()
	})
}

// SetRefundOfID sets the "refund_of_id" field.
func (u *ExpenseUpsertBulk) SetRefundOfID(v int) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetRefundOfID(v)
	})
}

// AddRefundOfID adds v to the "refund_of_id" field.
func (u *ExpenseUpsertBulk) AddRefundOfID(v int) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddRefundOfID(v)
	})
}

// UpdateRefundOfID sets the "refund_of_id" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateRefundOfID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateRefundOfID()
	})
}

// ClearRefundOfID clears the value of the "refund_of_id" field.
func (u *ExpenseUpsertBulk) ClearRefundOfID() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearRefundOfID()
	})
}

// SetCalcRubAmount sets the "calc_rub_amount" field.
func (u *ExpenseUpsertBulk) SetCalcRubAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetCalcRubAmount(v)
	})
}

// AddCalcRubAmount adds v to the "calc_rub_amount" field.
func (u *ExpenseUpsertBulk) AddCalcRubAmount(v int64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddCalcRubAmount(v)
	})
}

// UpdateCalcRubAmount sets the "calc_rub_amount" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateCalcRubAmount() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateCalcRubAmount()
	})
}

// ClearCalcRubAmount clears the value of the "calc_rub_amount" field.
func (u *ExpenseUpsertBulk) ClearCalcRubAmount() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearCalcRubAmount()
	})
}

// SetMeteredGB sets the "metered_gb" field.
func (u *ExpenseUpsertBulk) SetMeteredGB(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetMeteredGB(v)
	})
}

// AddMeteredGB adds v to the "metered_gb" field.
func (u *ExpenseUpsertBulk) AddMeteredGB(v float64) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.AddMeteredGB(v)
	})
}

// UpdateMeteredGB sets the "metered_gb" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateMeteredGB() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateMeteredGB()
	})
}

// ClearMeteredGB clears the value of the "metered_gb" field.
func (u *ExpenseUpsertBulk) ClearMeteredGB() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearMeteredGB()
	})
}

// SetPeriod sets the "period" field.
func (u *ExpenseUpsertBulk) SetPeriod(v string) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdatePeriod() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdatePeriod()
	})
}

// ClearPeriod clears the value of the "period" field.
func (u *ExpenseUpsertBulk) ClearPeriod() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearPeriod()
	})
}

// SetNote sets the "note" field.
func (u *ExpenseUpsertBulk) SetNote(v string) *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ExpenseUpsertBulk) UpdateNote() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ExpenseUpsertBulk) ClearNote() *ExpenseUpsertBulk {
	return u.Update(func(s *ExpenseUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *ExpenseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExpenseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExpenseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpenseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
