// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"vpn-control/ent/expenseitem"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExpenseItem is the model entity for the ExpenseItem schema.
type ExpenseItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// RwProviderUUID holds the value of the "rw_provider_uuid" field.
	RwProviderUUID string `json:"rw_provider_uuid,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Pricing holds the value of the "pricing" field.
	Pricing expenseitem.Pricing `json:"pricing,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Period holds the value of the "period" field.
	Period expenseitem.Period `json:"period,omitempty"`
	// FeePercent holds the value of the "fee_percent" field.
	FeePercent float64 `json:"fee_percent,omitempty"`
	// SharePercent holds the value of the "share_percent" field.
	SharePercent float64 `json:"share_percent,omitempty"`
	// PricePerGB holds the value of the "price_per_gb" field.
	PricePerGB int64 `json:"price_per_gb,omitempty"`
	// MinCharge holds the value of the "min_charge" field.
	MinCharge int64 `json:"min_charge,omitempty"`
	// RwNodeUUID holds the value of the "rw_node_uuid" field.
	RwNodeUUID string `json:"rw_node_uuid,omitempty"`
	// RwSquadUUID holds the value of the "rw_squad_uuid" field.
	RwSquadUUID string `json:"rw_squad_uuid,omitempty"`
	// NextDueDate holds the value of the "next_due_date" field.
	NextDueDate *time.Time `json:"next_due_date,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExpenseItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case expenseitem.FieldActive:
			values[i] = new(sql.NullBool)
		case expenseitem.FieldFeePercent, expenseitem.FieldSharePercent:
			values[i] = new(sql.NullFloat64)
		case expenseitem.FieldID, expenseitem.FieldAmount, expenseitem.FieldPricePerGB, expenseitem.FieldMinCharge:
			values[i] = new(sql.NullInt64)
		case expenseitem.FieldName, expenseitem.FieldProvider, expenseitem.FieldRwProviderUUID, expenseitem.FieldCurrency, expenseitem.FieldPricing, expenseitem.FieldPeriod, expenseitem.FieldRwNodeUUID, expenseitem.FieldRwSquadUUID, expenseitem.FieldNotes:
			values[i] = new(sql.NullString)
		case expenseitem.FieldCreatedAt, expenseitem.FieldUpdatedAt, expenseitem.FieldNextDueDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExpenseItem fields.
func (_m *ExpenseItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case expenseitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case expenseitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case expenseitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case expenseitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case expenseitem.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case expenseitem.FieldRwProviderUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rw_provider_uuid", values[i])
			} else if value.Valid {
				_m.RwProviderUUID = value.String
			}
		case expenseitem.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case expenseitem.FieldPricing:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing", values[i])
			} else if value.Valid {
				_m.Pricing = expenseitem.Pricing(value.String)
			}
		case expenseitem.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case expenseitem.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = expenseitem.Period(value.String)
			}
		case expenseitem.FieldFeePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_percent", values[i])
			} else if value.Valid {
				_m.FeePercent = value.Float64
			}
		case expenseitem.FieldSharePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field share_percent", values[i])
			} else if value.Valid {
				_m.SharePercent = value.Float64
			}
		case expenseitem.FieldPricePerGB:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_per_gb", values[i])
			} else if value.Valid {
				_m.PricePerGB = value.Int64
			}
		case expenseitem.FieldMinCharge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_charge", values[i])
			} else if value.Valid {
				_m.MinCharge = value.Int64
			}
		case expenseitem.FieldRwNodeUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rw_node_uuid", values[i])
			} else if value.Valid {
				_m.RwNodeUUID = value.String
			}
		case expenseitem.FieldRwSquadUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rw_squad_uuid", values[i])
			} else if value.Valid {
				_m.RwSquadUUID = value.String
			}
		case expenseitem.FieldNextDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_due_date", values[i])
			} else if value.Valid {
				_m.NextDueDate = new(time.Time)
				*_m.NextDueDate = value.Time
			}
		case expenseitem.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case expenseitem.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExpenseItem.
// This includes values selected through modifiers, order, etc.
func (_m *ExpenseItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExpenseItem.
// Note that you need to call ExpenseItem.Unwrap() before calling this method if this ExpenseItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExpenseItem) Update() *ExpenseItemUpdateOne {
	return NewExpenseItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExpenseItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExpenseItem) Unwrap() *ExpenseItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExpenseItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExpenseItem) String() string {
	var builder strings.Builder
	builder.WriteString("ExpenseItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("rw_provider_uuid=")
	builder.WriteString(_m.RwProviderUUID)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("pricing=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pricing))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(fmt.Sprintf("%v", _m.Period))
	builder.WriteString(", ")
	builder.WriteString("fee_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeePercent))
	builder.WriteString(", ")
	builder.WriteString("share_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharePercent))
	builder.WriteString(", ")
	builder.WriteString("price_per_gb=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricePerGB))
	builder.WriteString(", ")
	builder.WriteString("min_charge=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinCharge))
	builder.WriteString(", ")
	builder.WriteString("rw_node_uuid=")
	builder.WriteString(_m.RwNodeUUID)
	builder.WriteString(", ")
	builder.WriteString("rw_squad_uuid=")
	builder.WriteString(_m.RwSquadUUID)
	builder.WriteString(", ")
	if v := _m.NextDueDate; v != nil {
		builder.WriteString("next_due_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// ExpenseItems is a parsable slice of ExpenseItem.
type ExpenseItems []*ExpenseItem
