// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"vpn-control/ent/extension"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Extension is the model entity for the Extension schema.
type Extension struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind extension.Kind `json:"kind,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID int `json:"customer_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int `json:"subscription_id,omitempty"`
	// SubscriptionAddonID holds the value of the "subscription_addon_id" field.
	SubscriptionAddonID *int `json:"subscription_addon_id,omitempty"`
	// PaymentID holds the value of the "payment_id" field.
	PaymentID *int `json:"payment_id,omitempty"`
	// Months holds the value of the "months" field.
	Months int `json:"months,omitempty"`
	// Days holds the value of the "days" field.
	Days int `json:"days,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// FromAt holds the value of the "from_at" field.
	FromAt *time.Time `json:"from_at,omitempty"`
	// ToAt holds the value of the "to_at" field.
	ToAt *time.Time `json:"to_at,omitempty"`
	// LedgerEntryID holds the value of the "ledger_entry_id" field.
	LedgerEntryID *int `json:"ledger_entry_id,omitempty"`
	// Status holds the value of the "status" field.
	Status extension.Status `json:"status,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor        string `json:"actor,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Extension) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case extension.FieldID, extension.FieldCustomerID, extension.FieldSubscriptionID, extension.FieldSubscriptionAddonID, extension.FieldPaymentID, extension.FieldMonths, extension.FieldDays, extension.FieldAmount, extension.FieldLedgerEntryID:
			values[i] = new(sql.NullInt64)
		case extension.FieldKind, extension.FieldStatus, extension.FieldError, extension.FieldActor:
			values[i] = new(sql.NullString)
		case extension.FieldCreatedAt, extension.FieldUpdatedAt, extension.FieldFromAt, extension.FieldToAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Extension fields.
func (_m *Extension) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case extension.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case extension.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case extension.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case extension.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = extension.Kind(value.String)
			}
		case extension.FieldCustomerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = int(value.Int64)
			}
		case extension.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int)
				*_m.SubscriptionID = int(value.Int64)
			}
		case extension.FieldSubscriptionAddonID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_addon_id", values[i])
			} else if value.Valid {
				_m.SubscriptionAddonID = new(int)
				*_m.SubscriptionAddonID = int(value.Int64)
			}
		case extension.FieldPaymentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_id", values[i])
			} else if value.Valid {
				_m.PaymentID = new(int)
				*_m.PaymentID = int(value.Int64)
			}
		case extension.FieldMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field months", values[i])
			} else if value.Valid {
				_m.Months = int(value.Int64)
			}
		case extension.FieldDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field days", values[i])
			} else if value.Valid {
				_m.Days = int(value.Int64)
			}
		case extension.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case extension.FieldFromAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field from_at", values[i])
			} else if value.Valid {
				_m.FromAt = new(time.Time)
				*_m.FromAt = value.Time
			}
		case extension.FieldToAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field to_at", values[i])
			} else if value.Valid {
				_m.ToAt = new(time.Time)
				*_m.ToAt = value.Time
			}
		case extension.FieldLedgerEntryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_entry_id", values[i])
			} else if value.Valid {
				_m.LedgerEntryID = new(int)
				*_m.LedgerEntryID = int(value.Int64)
			}
		case extension.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = extension.Status(value.String)
			}
		case extension.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case extension.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Extension.
// This includes values selected through modifiers, order, etc.
func (_m *Extension) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Extension.
// Note that you need to call Extension.Unwrap() before calling this method if this Extension
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Extension) Update() *ExtensionUpdateOne {
	return NewExtensionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Extension entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Extension) Unwrap() *Extension {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Extension is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Extension) String() string {
	var builder strings.Builder
	builder.WriteString("Extension(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomerID))
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionAddonID; v != nil {
		builder.WriteString("subscription_addon_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PaymentID; v != nil {
		builder.WriteString("payment_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("months=")
	builder.WriteString(fmt.Sprintf("%v", _m.Months))
	builder.WriteString(", ")
	builder.WriteString("days=")
	builder.WriteString(fmt.Sprintf("%v", _m.Days))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	if v := _m.FromAt; v != nil {
		builder.WriteString("from_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ToAt; v != nil {
		builder.WriteString("to_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LedgerEntryID; v != nil {
		builder.WriteString("ledger_entry_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(_m.Actor)
	builder.WriteByte(')')
	return builder.String()
}

// Extensions is a parsable slice of Extension.
type Extensions []*Extension
