// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/extension"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExtensionCreate is the builder for creating a Extension entity.
type ExtensionCreate struct {
	config
	mutation *ExtensionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExtensionCreate) SetCreatedAt(v time.Time) *ExtensionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableCreatedAt(v *time.Time) *ExtensionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExtensionCreate) SetUpdatedAt(v time.Time) *ExtensionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableUpdatedAt(v *time.Time) *ExtensionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ExtensionCreate) SetKind(v extension.Kind) *ExtensionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *ExtensionCreate) SetCustomerID(v int) *ExtensionCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *ExtensionCreate) SetSubscriptionID(v int) *ExtensionCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableSubscriptionID(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetSubscriptionAddonID sets the "subscription_addon_id" field.
func (_c *ExtensionCreate) SetSubscriptionAddonID(v int) *ExtensionCreate {
	_c.mutation.SetSubscriptionAddonID(v)
	return _c
}

// SetNillableSubscriptionAddonID sets the "subscription_addon_id" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableSubscriptionAddonID(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetSubscriptionAddonID(*v)
	}
	return _c
}

// SetPaymentID sets the "payment_id" field.
func (_c *ExtensionCreate) SetPaymentID(v int) *ExtensionCreate {
	_c.mutation.SetPaymentID(v)
	return _c
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillablePaymentID(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetPaymentID(*v)
	}
	return _c
}

// SetMonths sets the "months" field.
func (_c *ExtensionCreate) SetMonths(v int) *ExtensionCreate {
	_c.mutation.SetMonths(v)
	return _c
}

// SetNillableMonths sets the "months" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableMonths(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetMonths(*v)
	}
	return _c
}

// SetDays sets the "days" field.
func (_c *ExtensionCreate) SetDays(v int) *ExtensionCreate {
	_c.mutation.SetDays(v)
	return _c
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableDays(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetDays(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ExtensionCreate) SetAmount(v int64) *ExtensionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableAmount(v *int64) *ExtensionCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetFromAt sets the "from_at" field.
func (_c *ExtensionCreate) SetFromAt(v time.Time) *ExtensionCreate {
	_c.mutation.SetFromAt(v)
	return _c
}

// SetNillableFromAt sets the "from_at" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableFromAt(v *time.Time) *ExtensionCreate {
	if v != nil {
		_c.SetFromAt(*v)
	}
	return _c
}

// SetToAt sets the "to_at" field.
func (_c *ExtensionCreate) SetToAt(v time.Time) *ExtensionCreate {
	_c.mutation.SetToAt(v)
	return _c
}

// SetNillableToAt sets the "to_at" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableToAt(v *time.Time) *ExtensionCreate {
	if v != nil {
		_c.SetToAt(*v)
	}
	return _c
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (_c *ExtensionCreate) SetLedgerEntryID(v int) *ExtensionCreate {
	_c.mutation.SetLedgerEntryID(v)
	return _c
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableLedgerEntryID(v *int) *ExtensionCreate {
	if v != nil {
		_c.SetLedgerEntryID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExtensionCreate) SetStatus(v extension.Status) *ExtensionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetError sets the "error" field.
func (_c *ExtensionCreate) SetError(v string) *ExtensionCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableError(v *string) *ExtensionCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetActor sets the "actor" field.
func (_c *ExtensionCreate) SetActor(v string) *ExtensionCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *ExtensionCreate) SetNillableActor(v *string) *ExtensionCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// Mutation returns the ExtensionMutation object of the builder.
func (_c *ExtensionCreate) Mutation() *ExtensionMutation {
	return _c.mutation
}

// Save creates the Extension in the database.
func (_c *ExtensionCreate) Save(ctx context.Context) (*Extension, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExtensionCreate) SaveX(ctx context.Context) *Extension {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExtensionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := extension.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := extension.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Months(); !ok {
		v := extension.DefaultMonths
		_c.mutation.SetMonths(v)
	}
	if _, ok := _c.mutation.Days(); !ok {
		v := extension.DefaultDays
		_c.mutation.SetDays(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := extension.DefaultAmount
		_c.mutation.SetAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExtensionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Extension.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Extension.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Extension.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := extension.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Extension.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Extension.customer_id"`)}
	}
	if _, ok := _c.mutation.Months(); !ok {
		return &ValidationError{Name: "months", err: errors.New(`ent: missing required field "Extension.months"`)}
	}
	if _, ok := _c.mutation.Days(); !ok {
		return &ValidationError{Name: "days", err: errors.New(`ent: missing required field "Extension.days"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Extension.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Extension.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := extension.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Extension.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ExtensionCreate) sqlSave(ctx context.Context) (*Extension, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExtensionCreate) createSpec() (*Extension, *sqlgraph.CreateSpec) {
	var (
		_node = &Extension{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(extension.Table, sqlgraph.NewFieldSpec(extension.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(extension.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(extension.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(extension.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(extension.FieldCustomerID, field.TypeInt, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(extension.FieldSubscriptionID, field.TypeInt, value)
		_node.SubscriptionID = &value
	}
	if value, ok := _c.mutation.SubscriptionAddonID(); ok {
		_spec.SetField(extension.FieldSubscriptionAddonID, field.TypeInt, value)
		_node.SubscriptionAddonID = &value
	}
	if value, ok := _c.mutation.PaymentID(); ok {
		_spec.SetField(extension.FieldPaymentID, field.TypeInt, value)
		_node.PaymentID = &value
	}
	if value, ok := _c.mutation.Months(); ok {
		_spec.SetField(extension.FieldMonths, field.TypeInt, value)
		_node.Months = value
	}
	if value, ok := _c.mutation.Days(); ok {
		_spec.SetField(extension.FieldDays, field.TypeInt, value)
		_node.Days = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(extension.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.FromAt(); ok {
		_spec.SetField(extension.FieldFromAt, field.TypeTime, value)
		_node.FromAt = &value
	}
	if value, ok := _c.mutation.ToAt(); ok {
		_spec.SetField(extension.FieldToAt, field.TypeTime, value)
		_node.ToAt = &value
	}
	if value, ok := _c.mutation.LedgerEntryID(); ok {
		_spec.SetField(extension.FieldLedgerEntryID, field.TypeInt, value)
		_node.LedgerEntryID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(extension.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(extension.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(extension.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Extension.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionCreate) OnConflict(opts ...sql.ConflictOption) *ExtensionUpsertOne {
	_c.conflict = opts
	return &ExtensionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Extension.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionCreate) OnConflictColumns(columns ...string) *ExtensionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionUpsertOne{
		create: _c,
	}
}

type (
	// ExtensionUpsertOne is the builder for "upsert"-ing
	//  one Extension node.
	ExtensionUpsertOne struct {
		create *ExtensionCreate
	}

	// ExtensionUpsert is the "OnConflict" setter.
	ExtensionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionUpsert) SetUpdatedAt(v time.Time) *ExtensionUpsert {
	u.Set(extension.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateUpdatedAt() *ExtensionUpsert {
	u.SetExcluded(extension.FieldUpdatedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *ExtensionUpsert) SetKind(v extension.Kind) *ExtensionUpsert {
	u.Set(extension.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateKind() *ExtensionUpsert {
	u.SetExcluded(extension.FieldKind)
	return u
}

// SetCustomerID sets the "customer_id" field.
func (u *ExtensionUpsert) SetCustomerID(v int) *ExtensionUpsert {
	u.Set(extension.FieldCustomerID, v)
	return u
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateCustomerID() *ExtensionUpsert {
	u.SetExcluded(extension.FieldCustomerID)
	return u
}

// AddCustomerID adds v to the "customer_id" field.
func (u *ExtensionUpsert) AddCustomerID(v int) *ExtensionUpsert {
	u.Add(extension.FieldCustomerID, v)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *ExtensionUpsert) SetSubscriptionID(v int) *ExtensionUpsert {
	u.Set(extension.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateSubscriptionID() *ExtensionUpsert {
	u.SetExcluded(extension.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *ExtensionUpsert) AddSubscriptionID(v int) *ExtensionUpsert {
	u.Add(extension.FieldSubscriptionID, v)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *ExtensionUpsert) ClearSubscriptionID() *ExtensionUpsert {
	u.SetNull(extension.FieldSubscriptionID)
	return u
}

// SetSubscriptionAddonID sets the "subscription_addon_id" field.
func (u *ExtensionUpsert) SetSubscriptionAddonID(v int) *ExtensionUpsert {
	u.Set(extension.FieldSubscriptionAddonID, v)
	return u
}

// UpdateSubscriptionAddonID sets the "subscription_addon_id" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateSubscriptionAddonID() *ExtensionUpsert {
	u.SetExcluded(extension.FieldSubscriptionAddonID)
	return u
}

// AddSubscriptionAddonID adds v to the "subscription_addon_id" field.
func (u *ExtensionUpsert) AddSubscriptionAddonID(v int) *ExtensionUpsert {
	u.Add(extension.FieldSubscriptionAddonID, v)
	return u
}

// ClearSubscriptionAddonID clears the value of the "subscription_addon_id" field.
func (u *ExtensionUpsert) ClearSubscriptionAddonID() *ExtensionUpsert {
	u.SetNull(extension.FieldSubscriptionAddonID)
	return u
}

// SetPaymentID sets the "payment_id" field.
func (u *ExtensionUpsert) SetPaymentID(v int) *ExtensionUpsert {
	u.Set(extension.FieldPaymentID, v)
	return u
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdatePaymentID() *ExtensionUpsert {
	u.SetExcluded(extension.FieldPaymentID)
	return u
}

// AddPaymentID adds v to the "payment_id" field.
func (u *ExtensionUpsert) AddPaymentID(v int) *ExtensionUpsert {
	u.Add(extension.FieldPaymentID, v)
	return u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *ExtensionUpsert) ClearPaymentID() *ExtensionUpsert {
	u.SetNull(extension.FieldPaymentID)
	return u
}

// SetMonths sets the "months" field.
func (u *ExtensionUpsert) SetMonths(v int) *ExtensionUpsert {
	u.Set(extension.FieldMonths, v)
	return u
}

// UpdateMonths sets the "months" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateMonths() *ExtensionUpsert {
	u.SetExcluded(extension.FieldMonths)
	return u
}

// AddMonths adds v to the "months" field.
func (u *ExtensionUpsert) AddMonths(v int) *ExtensionUpsert {
	u.Add(extension.FieldMonths, v)
	return u
}

// SetDays sets the "days" field.
func (u *ExtensionUpsert) SetDays(v int) *ExtensionUpsert {
	u.Set(extension.FieldDays, v)
	return u
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateDays() *ExtensionUpsert {
	u.SetExcluded(extension.FieldDays)
	return u
}

// AddDays adds v to the "days" field.
func (u *ExtensionUpsert) AddDays(v int) *ExtensionUpsert {
	u.Add(extension.FieldDays, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *ExtensionUpsert) SetAmount(v int64) *ExtensionUpsert {
	u.Set(extension.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateAmount() *ExtensionUpsert {
	u.SetExcluded(extension.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ExtensionUpsert) AddAmount(v int64) *ExtensionUpsert {
	u.Add(extension.FieldAmount, v)
	return u
}

// SetFromAt sets the "from_at" field.
func (u *ExtensionUpsert) SetFromAt(v time.Time) *ExtensionUpsert {
	u.Set(extension.FieldFromAt, v)
	return u
}

// UpdateFromAt sets the "from_at" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateFromAt() *ExtensionUpsert {
	u.SetExcluded(extension.FieldFromAt)
	return u
}

// ClearFromAt clears the value of the "from_at" field.
func (u *ExtensionUpsert) ClearFromAt() *ExtensionUpsert {
	u.SetNull(extension.FieldFromAt)
	return u
}

// SetToAt sets the "to_at" field.
func (u *ExtensionUpsert) SetToAt(v time.Time) *ExtensionUpsert {
	u.Set(extension.FieldToAt, v)
	return u
}

// UpdateToAt sets the "to_at" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateToAt() *ExtensionUpsert {
	u.SetExcluded(extension.FieldToAt)
	return u
}

// ClearToAt clears the value of the "to_at" field.
func (u *ExtensionUpsert) ClearToAt() *ExtensionUpsert {
	u.SetNull(extension.FieldToAt)
	return u
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (u *ExtensionUpsert) SetLedgerEntryID(v int) *ExtensionUpsert {
	u.Set(extension.FieldLedgerEntryID, v)
	return u
}

// UpdateLedgerEntryID sets the "ledger_entry_id" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateLedgerEntryID() *ExtensionUpsert {
	u.SetExcluded(extension.FieldLedgerEntryID)
	return u
}

// AddLedgerEntryID adds v to the "ledger_entry_id" field.
func (u *ExtensionUpsert) AddLedgerEntryID(v int) *ExtensionUpsert {
	u.Add(extension.FieldLedgerEntryID, v)
	return u
}

// ClearLedgerEntryID clears the value of the "ledger_entry_id" field.
func (u *ExtensionUpsert) ClearLedgerEntryID() *ExtensionUpsert {
	u.SetNull(extension.FieldLedgerEntryID)
	return u
}

// SetStatus sets the "status" field.
func (u *ExtensionUpsert) SetStatus(v extension.Status) *ExtensionUpsert {
	u.Set(extension.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateStatus() *ExtensionUpsert {
	u.SetExcluded(extension.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *ExtensionUpsert) SetError(v string) *ExtensionUpsert {
	u.Set(extension.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateError() *ExtensionUpsert {
	u.SetExcluded(extension.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *ExtensionUpsert) ClearError() *ExtensionUpsert {
	u.SetNull(extension.FieldError)
	return u
}

// SetActor sets the "actor" field.
func (u *ExtensionUpsert) SetActor(v string) *ExtensionUpsert {
	u.Set(extension.FieldActor, v)
	return u
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *ExtensionUpsert) UpdateActor() *ExtensionUpsert {
	u.SetExcluded(extension.FieldActor)
	return u
}

// ClearActor clears the value of the "actor" field.
func (u *ExtensionUpsert) ClearActor() *ExtensionUpsert {
	u.SetNull(extension.FieldActor)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Extension.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionUpsertOne) UpdateNewValues() *ExtensionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(extension.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Extension.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExtensionUpsertOne) Ignore() *ExtensionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionUpsertOne) DoNothing() *ExtensionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionCreate.OnConflict
// documentation for more info.
func (u *ExtensionUpsertOne) Update(set func(*ExtensionUpsert)) *ExtensionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionUpsertOne) SetUpdatedAt(v time.Time) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateUpdatedAt() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *ExtensionUpsertOne) SetKind(v extension.Kind) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateKind() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateKind()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *ExtensionUpsertOne) SetCustomerID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetCustomerID(v)
	})
}

// AddCustomerID adds v to the "customer_id" field.
func (u *ExtensionUpsertOne) AddCustomerID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateCustomerID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateCustomerID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *ExtensionUpsertOne) SetSubscriptionID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *ExtensionUpsertOne) AddSubscriptionID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateSubscriptionID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *ExtensionUpsertOne) ClearSubscriptionID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetSubscriptionAddonID sets the "subscription_addon_id" field.
func (u *ExtensionUpsertOne) SetSubscriptionAddonID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetSubscriptionAddonID(v)
	})
}

// AddSubscriptionAddonID adds v to the "subscription_addon_id" field.
func (u *ExtensionUpsertOne) AddSubscriptionAddonID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddSubscriptionAddonID(v)
	})
}

// UpdateSubscriptionAddonID sets the "subscription_addon_id" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateSubscriptionAddonID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateSubscriptionAddonID()
	})
}

// ClearSubscriptionAddonID clears the value of the "subscription_addon_id" field.
func (u *ExtensionUpsertOne) ClearSubscriptionAddonID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearSubscriptionAddonID()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *ExtensionUpsertOne) SetPaymentID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetPaymentID(v)
	})
}

// AddPaymentID adds v to the "payment_id" field.
func (u *ExtensionUpsertOne) AddPaymentID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdatePaymentID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *ExtensionUpsertOne) ClearPaymentID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearPaymentID()
	})
}

// SetMonths sets the "months" field.
func (u *ExtensionUpsertOne) SetMonths(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetMonths(v)
	})
}

// AddMonths adds v to the "months" field.
func (u *ExtensionUpsertOne) AddMonths(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddMonths(v)
	})
}

// UpdateMonths sets the "months" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateMonths() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateMonths()
	})
}

// SetDays sets the "days" field.
func (u *ExtensionUpsertOne) SetDays(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *ExtensionUpsertOne) AddDays(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateDays() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateDays()
	})
}

// SetAmount sets the "amount" field.
func (u *ExtensionUpsertOne) SetAmount(v int64) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExtensionUpsertOne) AddAmount(v int64) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateAmount() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateAmount()
	})
}

// SetFromAt sets the "from_at" field.
func (u *ExtensionUpsertOne) SetFromAt(v time.Time) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetFromAt(v)
	})
}

// UpdateFromAt sets the "from_at" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateFromAt() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateFromAt()
	})
}

// ClearFromAt clears the value of the "from_at" field.
func (u *ExtensionUpsertOne) ClearFromAt() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearFromAt()
	})
}

// SetToAt sets the "to_at" field.
func (u *ExtensionUpsertOne) SetToAt(v time.Time) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetToAt(v)
	})
}

// UpdateToAt sets the "to_at" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateToAt() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateToAt()
	})
}

// ClearToAt clears the value of the "to_at" field.
func (u *ExtensionUpsertOne) ClearToAt() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearToAt()
	})
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (u *ExtensionUpsertOne) SetLedgerEntryID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetLedgerEntryID(v)
	})
}

// AddLedgerEntryID adds v to the "ledger_entry_id" field.
func (u *ExtensionUpsertOne) AddLedgerEntryID(v int) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddLedgerEntryID(v)
	})
}

// UpdateLedgerEntryID sets the "ledger_entry_id" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateLedgerEntryID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateLedgerEntryID()
	})
}

// ClearLedgerEntryID clears the value of the "ledger_entry_id" field.
func (u *ExtensionUpsertOne) ClearLedgerEntryID() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearLedgerEntryID()
	})
}

// SetStatus sets the "status" field.
func (u *ExtensionUpsertOne) SetStatus(v extension.Status) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateStatus() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *ExtensionUpsertOne) SetError(v string) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateError() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ExtensionUpsertOne) ClearError() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearError()
	})
}

// SetActor sets the "actor" field.
func (u *ExtensionUpsertOne) SetActor(v string) *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetActor(v)
	})
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *ExtensionUpsertOne) UpdateActor() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateActor()
	})
}

// ClearActor clears the value of the "actor" field.
func (u *ExtensionUpsertOne) ClearActor() *ExtensionUpsertOne {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearActor()
	})
}

// Exec executes the query.
func (u *ExtensionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExtensionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExtensionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExtensionCreateBulk is the builder for creating many Extension entities in bulk.
type ExtensionCreateBulk struct {
	config
	err      error
	builders []*ExtensionCreate
	conflict []sql.ConflictOption
}

// Save creates the Extension entities in the database.
func (_c *ExtensionCreateBulk) Save(ctx context.Context) ([]*Extension, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Extension, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtensionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExtensionCreateBulk) SaveX(ctx context.Context) []*Extension {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Extension.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExtensionUpsertBulk {
	_c.conflict = opts
	return &ExtensionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Extension.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionCreateBulk) OnConflictColumns(columns ...string) *ExtensionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionUpsertBulk{
		create: _c,
	}
}

// ExtensionUpsertBulk is the builder for "upsert"-ing
// a bulk of Extension nodes.
type ExtensionUpsertBulk struct {
	create *ExtensionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Extension.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionUpsertBulk) UpdateNewValues() *ExtensionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(extension.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Extension.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExtensionUpsertBulk) Ignore() *ExtensionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionUpsertBulk) DoNothing() *ExtensionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionCreateBulk.OnConflict
// documentation for more info.
func (u *ExtensionUpsertBulk) Update(set func(*ExtensionUpsert)) *ExtensionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionUpsertBulk) SetUpdatedAt(v time.Time) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateUpdatedAt() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *ExtensionUpsertBulk) SetKind(v extension.Kind) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateKind() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateKind()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *ExtensionUpsertBulk) SetCustomerID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetCustomerID(v)
	})
}

// AddCustomerID adds v to the "customer_id" field.
func (u *ExtensionUpsertBulk) AddCustomerID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateCustomerID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateCustomerID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *ExtensionUpsertBulk) SetSubscriptionID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *ExtensionUpsertBulk) AddSubscriptionID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateSubscriptionID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *ExtensionUpsertBulk) ClearSubscriptionID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetSubscriptionAddonID sets the "subscription_addon_id" field.
func (u *ExtensionUpsertBulk) SetSubscriptionAddonID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetSubscriptionAddonID(v)
	})
}

// AddSubscriptionAddonID adds v to the "subscription_addon_id" field.
func (u *ExtensionUpsertBulk) AddSubscriptionAddonID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddSubscriptionAddonID(v)
	})
}

// UpdateSubscriptionAddonID sets the "subscription_addon_id" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateSubscriptionAddonID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateSubscriptionAddonID()
	})
}

// ClearSubscriptionAddonID clears the value of the "subscription_addon_id" field.
func (u *ExtensionUpsertBulk) ClearSubscriptionAddonID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearSubscriptionAddonID()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *ExtensionUpsertBulk) SetPaymentID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetPaymentID(v)
	})
}

// AddPaymentID adds v to the "payment_id" field.
func (u *ExtensionUpsertBulk) AddPaymentID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdatePaymentID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *ExtensionUpsertBulk) ClearPaymentID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearPaymentID()
	})
}

// SetMonths sets the "months" field.
func (u *ExtensionUpsertBulk) SetMonths(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetMonths(v)
	})
}

// AddMonths adds v to the "months" field.
func (u *ExtensionUpsertBulk) AddMonths(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddMonths(v)
	})
}

// UpdateMonths sets the "months" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateMonths() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateMonths()
	})
}

// SetDays sets the "days" field.
func (u *ExtensionUpsertBulk) SetDays(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *ExtensionUpsertBulk) AddDays(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateDays() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateDays()
	})
}

// SetAmount sets the "amount" field.
func (u *ExtensionUpsertBulk) SetAmount(v int64) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExtensionUpsertBulk) AddAmount(v int64) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateAmount() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateAmount()
	})
}

// SetFromAt sets the "from_at" field.
func (u *ExtensionUpsertBulk) SetFromAt(v time.Time) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetFromAt(v)
	})
}

// UpdateFromAt sets the "from_at" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateFromAt() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateFromAt()
	})
}

// ClearFromAt clears the value of the "from_at" field.
func (u *ExtensionUpsertBulk) ClearFromAt() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearFromAt()
	})
}

// SetToAt sets the "to_at" field.
func (u *ExtensionUpsertBulk) SetToAt(v time.Time) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetToAt(v)
	})
}

// UpdateToAt sets the "to_at" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateToAt() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateToAt()
	})
}

// ClearToAt clears the value of the "to_at" field.
func (u *ExtensionUpsertBulk) ClearToAt() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearToAt()
	})
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (u *ExtensionUpsertBulk) SetLedgerEntryID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetLedgerEntryID(v)
	})
}

// AddLedgerEntryID adds v to the "ledger_entry_id" field.
func (u *ExtensionUpsertBulk) AddLedgerEntryID(v int) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.AddLedgerEntryID(v)
	})
}

// UpdateLedgerEntryID sets the "ledger_entry_id" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateLedgerEntryID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateLedgerEntryID()
	})
}

// ClearLedgerEntryID clears the value of the "ledger_entry_id" field.
func (u *ExtensionUpsertBulk) ClearLedgerEntryID() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearLedgerEntryID()
	})
}

// SetStatus sets the "status" field.
func (u *ExtensionUpsertBulk) SetStatus(v extension.Status) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateStatus() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *ExtensionUpsertBulk) SetError(v string) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateError() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ExtensionUpsertBulk) ClearError() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearError()
	})
}

// SetActor sets the "actor" field.
func (u *ExtensionUpsertBulk) SetActor(v string) *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.SetActor(v)
	})
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *ExtensionUpsertBulk) UpdateActor() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.UpdateActor()
	})
}

// ClearActor clears the value of the "actor" field.
func (u *ExtensionUpsertBulk) ClearActor() *ExtensionUpsertBulk {
	return u.Update(func(s *ExtensionUpsert) {
		s.ClearActor()
	})
}

// Exec executes the query.
func (u *ExtensionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExtensionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
