// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"vpn-control/ent/fxrate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FxRateCreate is the builder for creating a FxRate entity.
type FxRateCreate struct {
	config
	mutation *FxRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDate sets the "date" field.
func (_c *FxRateCreate) SetDate(v string) *FxRateCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *FxRateCreate) SetCurrency(v string) *FxRateCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetBase sets the "base" field.
func (_c *FxRateCreate) SetBase(v string) *FxRateCreate {
	_c.mutation.SetBase(v)
	return _c
}

// SetNillableBase sets the "base" field if the given value is not nil.
func (_c *FxRateCreate) SetNillableBase(v *string) *FxRateCreate {
	if v != nil {
		_c.SetBase(*v)
	}
	return _c
}

// SetRate sets the "rate" field.
func (_c *FxRateCreate) SetRate(v float64) *FxRateCreate {
	_c.mutation.SetRate(v)
	return _c
}

// Mutation returns the FxRateMutation object of the builder.
func (_c *FxRateCreate) Mutation() *FxRateMutation {
	return _c.mutation
}

// Save creates the FxRate in the database.
func (_c *FxRateCreate) Save(ctx context.Context) (*FxRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FxRateCreate) SaveX(ctx context.Context) *FxRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FxRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FxRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FxRateCreate) defaults() {
	if _, ok := _c.mutation.Base(); !ok {
		v := fxrate.DefaultBase
		_c.mutation.SetBase(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FxRateCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "FxRate.date"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "FxRate.currency"`)}
	}
	if _, ok := _c.mutation.Base(); !ok {
		return &ValidationError{Name: "base", err: errors.New(`ent: missing required field "FxRate.base"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "FxRate.rate"`)}
	}
	return nil
}

func (_c *FxRateCreate) sqlSave(ctx context.Context) (*FxRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FxRateCreate) createSpec() (*FxRate, *sqlgraph.CreateSpec) {
	var (
		_node = &FxRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fxrate.Table, sqlgraph.NewFieldSpec(fxrate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(fxrate.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(fxrate.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Base(); ok {
		_spec.SetField(fxrate.FieldBase, field.TypeString, value)
		_node.Base = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(fxrate.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FxRate.Create().
//		SetDate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FxRateUpsert) {
//			SetDate(v+v).
//		}).
//		Exec(ctx)
func (_c *FxRateCreate) OnConflict(opts ...sql.ConflictOption) *FxRateUpsertOne {
	_c.conflict = opts
	return &FxRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FxRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FxRateCreate) OnConflictColumns(columns ...string) *FxRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FxRateUpsertOne{
		create: _c,
	}
}

type (
	// FxRateUpsertOne is the builder for "upsert"-ing
	//  one FxRate node.
	FxRateUpsertOne struct {
		create *FxRateCreate
	}

	// FxRateUpsert is the "OnConflict" setter.
	FxRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetDate sets the "date" field.
func (u *FxRateUpsert) SetDate(v string) *FxRateUpsert {
	u.Set(fxrate.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *FxRateUpsert) UpdateDate() *FxRateUpsert {
	u.SetExcluded(fxrate.FieldDate)
	return u
}

// SetCurrency sets the "currency" field.
func (u *FxRateUpsert) SetCurrency(v string) *FxRateUpsert {
	u.Set(fxrate.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FxRateUpsert) UpdateCurrency() *FxRateUpsert {
	u.SetExcluded(fxrate.FieldCurrency)
	return u
}

// SetBase sets the "base" field.
func (u *FxRateUpsert) SetBase(v string) *FxRateUpsert {
	u.Set(fxrate.FieldBase, v)
	return u
}

// UpdateBase sets the "base" field to the value that was provided on create.
func (u *FxRateUpsert) UpdateBase() *FxRateUpsert {
	u.SetExcluded(fxrate.FieldBase)
	return u
}

// SetRate sets the "rate" field.
func (u *FxRateUpsert) SetRate(v float64) *FxRateUpsert {
	u.Set(fxrate.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *FxRateUpsert) UpdateRate() *FxRateUpsert {
	u.SetExcluded(fxrate.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *FxRateUpsert) AddRate(v float64) *FxRateUpsert {
	u.Add(fxrate.FieldRate, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FxRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FxRateUpsertOne) UpdateNewValues() *FxRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FxRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FxRateUpsertOne) Ignore() *FxRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FxRateUpsertOne) DoNothing() *FxRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FxRateCreate.OnConflict
// documentation for more info.
func (u *FxRateUpsertOne) Update(set func(*FxRateUpsert)) *FxRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FxRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetDate sets the "date" field.
func (u *FxRateUpsertOne) SetDate(v string) *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *FxRateUpsertOne) UpdateDate() *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateDate()
	})
}

// SetCurrency sets the "currency" field.
func (u *FxRateUpsertOne) SetCurrency(v string) *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FxRateUpsertOne) UpdateCurrency() *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateCurrency()
	})
}

// SetBase sets the "base" field.
func (u *FxRateUpsertOne) SetBase(v string) *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.SetBase(v)
	})
}

// UpdateBase sets the "base" field to the value that was provided on create.
func (u *FxRateUpsertOne) UpdateBase() *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateBase()
	})
}

// SetRate sets the "rate" field.
func (u *FxRateUpsertOne) SetRate(v float64) *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *FxRateUpsertOne) AddRate(v float64) *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *FxRateUpsertOne) UpdateRate() *FxRateUpsertOne {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateRate()
	})
}

// Exec executes the query.
func (u *FxRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FxRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FxRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FxRateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FxRateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FxRateCreateBulk is the builder for creating many FxRate entities in bulk.
type FxRateCreateBulk struct {
	config
	err      error
	builders []*FxRateCreate
	conflict []sql.ConflictOption
}

// Save creates the FxRate entities in the database.
func (_c *FxRateCreateBulk) Save(ctx context.Context) ([]*FxRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FxRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FxRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FxRateCreateBulk) SaveX(ctx context.Context) []*FxRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FxRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FxRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FxRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FxRateUpsert) {
//			SetDate(v+v).
//		}).
//		Exec(ctx)
func (_c *FxRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *FxRateUpsertBulk {
	_c.conflict = opts
	return &FxRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FxRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FxRateCreateBulk) OnConflictColumns(columns ...string) *FxRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FxRateUpsertBulk{
		create: _c,
	}
}

// FxRateUpsertBulk is the builder for "upsert"-ing
// a bulk of FxRate nodes.
type FxRateUpsertBulk struct {
	create *FxRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FxRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FxRateUpsertBulk) UpdateNewValues() *FxRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FxRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FxRateUpsertBulk) Ignore() *FxRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FxRateUpsertBulk) DoNothing() *FxRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FxRateCreateBulk.OnConflict
// documentation for more info.
func (u *FxRateUpsertBulk) Update(set func(*FxRateUpsert)) *FxRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FxRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetDate sets the "date" field.
func (u *FxRateUpsertBulk) SetDate(v string) *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *FxRateUpsertBulk) UpdateDate() *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateDate()
	})
}

// SetCurrency sets the "currency" field.
func (u *FxRateUpsertBulk) SetCurrency(v string) *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FxRateUpsertBulk) UpdateCurrency() *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateCurrency()
	})
}

// SetBase sets the "base" field.
func (u *FxRateUpsertBulk) SetBase(v string) *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.SetBase(v)
	})
}

// UpdateBase sets the "base" field to the value that was provided on create.
func (u *FxRateUpsertBulk) UpdateBase() *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateBase()
	})
}

// SetRate sets the "rate" field.
func (u *FxRateUpsertBulk) SetRate(v float64) *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *FxRateUpsertBulk) AddRate(v float64) *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *FxRateUpsertBulk) UpdateRate() *FxRateUpsertBulk {
	return u.Update(func(s *FxRateUpsert) {
		s.UpdateRate()
	})
}

// Exec executes the query.
func (u *FxRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FxRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FxRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FxRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
