// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/payment"
	"vpn-control/ent/predicate"
	"vpn-control/ent/referralaccrual"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReferralAccrualUpdate is the builder for updating ReferralAccrual entities.
type ReferralAccrualUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralAccrualMutation
}

// Where appends a list predicates to the ReferralAccrualUpdate builder.
func (_u *ReferralAccrualUpdate) Where(ps ...predicate.ReferralAccrual) *ReferralAccrualUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralAccrualUpdate) SetUpdatedAt(v time.Time) *ReferralAccrualUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralAccrualUpdate) SetReferrerID(v int) *ReferralAccrualUpdate {
	_u.mutation.ResetReferrerID()
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillableReferrerID(v *int) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// AddReferrerID adds value to the "referrer_id" field.
func (_u *ReferralAccrualUpdate) AddReferrerID(v int) *ReferralAccrualUpdate {
	_u.mutation.AddReferrerID(v)
	return _u
}

// SetRefereeID sets the "referee_id" field.
func (_u *ReferralAccrualUpdate) SetRefereeID(v int) *ReferralAccrualUpdate {
	_u.mutation.ResetRefereeID()
	_u.mutation.SetRefereeID(v)
	return _u
}

// SetNillableRefereeID sets the "referee_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillableRefereeID(v *int) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetRefereeID(*v)
	}
	return _u
}

// AddRefereeID adds value to the "referee_id" field.
func (_u *ReferralAccrualUpdate) AddRefereeID(v int) *ReferralAccrualUpdate {
	_u.mutation.AddRefereeID(v)
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *ReferralAccrualUpdate) SetPaymentID(v int) *ReferralAccrualUpdate {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillablePaymentID(v *int) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// SetPercent sets the "percent" field.
func (_u *ReferralAccrualUpdate) SetPercent(v float64) *ReferralAccrualUpdate {
	_u.mutation.ResetPercent()
	_u.mutation.SetPercent(v)
	return _u
}

// SetNillablePercent sets the "percent" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillablePercent(v *float64) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetPercent(*v)
	}
	return _u
}

// AddPercent adds value to the "percent" field.
func (_u *ReferralAccrualUpdate) AddPercent(v float64) *ReferralAccrualUpdate {
	_u.mutation.AddPercent(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralAccrualUpdate) SetAmount(v int64) *ReferralAccrualUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillableAmount(v *int64) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralAccrualUpdate) AddAmount(v int64) *ReferralAccrualUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *ReferralAccrualUpdate) SetDate(v time.Time) *ReferralAccrualUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillableDate(v *time.Time) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralAccrualUpdate) SetStatus(v referralaccrual.Status) *ReferralAccrualUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralAccrualUpdate) SetNillableStatus(v *referralaccrual.Status) *ReferralAccrualUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayment sets the "payment" edge to the Payment entity.
func (_u *ReferralAccrualUpdate) SetPayment(v *Payment) *ReferralAccrualUpdate {
	return _u.SetPaymentID(v.ID)
}

// Mutation returns the ReferralAccrualMutation object of the builder.
func (_u *ReferralAccrualUpdate) Mutation() *ReferralAccrualMutation {
	return _u.mutation
}

// ClearPayment clears the "payment" edge to the Payment entity.
func (_u *ReferralAccrualUpdate) ClearPayment() *ReferralAccrualUpdate {
	_u.mutation.ClearPayment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralAccrualUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralAccrualUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralAccrualUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralAccrualUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralAccrualUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralaccrual.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralAccrualUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := referralaccrual.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralAccrual.status": %w`, err)}
		}
	}
	if _u.mutation.PaymentCleared() && len(_u.mutation.PaymentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralAccrual.payment"`)
	}
	return nil
}

func (_u *ReferralAccrualUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralaccrual.Table, referralaccrual.Columns, sqlgraph.NewFieldSpec(referralaccrual.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralaccrual.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReferrerID(); ok {
		_spec.SetField(referralaccrual.FieldReferrerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferrerID(); ok {
		_spec.AddField(referralaccrual.FieldReferrerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefereeID(); ok {
		_spec.SetField(referralaccrual.FieldRefereeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefereeID(); ok {
		_spec.AddField(referralaccrual.FieldRefereeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Percent(); ok {
		_spec.SetField(referralaccrual.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercent(); ok {
		_spec.AddField(referralaccrual.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralaccrual.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralaccrual.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(referralaccrual.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralaccrual.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PaymentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralaccrual.PaymentTable,
			Columns: []string{referralaccrual.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralaccrual.PaymentTable,
			Columns: []string{referralaccrual.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralaccrual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralAccrualUpdateOne is the builder for updating a single ReferralAccrual entity.
type ReferralAccrualUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralAccrualMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralAccrualUpdateOne) SetUpdatedAt(v time.Time) *ReferralAccrualUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralAccrualUpdateOne) SetReferrerID(v int) *ReferralAccrualUpdateOne {
	_u.mutation.ResetReferrerID()
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillableReferrerID(v *int) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// AddReferrerID adds value to the "referrer_id" field.
func (_u *ReferralAccrualUpdateOne) AddReferrerID(v int) *ReferralAccrualUpdateOne {
	_u.mutation.AddReferrerID(v)
	return _u
}

// SetRefereeID sets the "referee_id" field.
func (_u *ReferralAccrualUpdateOne) SetRefereeID(v int) *ReferralAccrualUpdateOne {
	_u.mutation.ResetRefereeID()
	_u.mutation.SetRefereeID(v)
	return _u
}

// SetNillableRefereeID sets the "referee_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillableRefereeID(v *int) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetRefereeID(*v)
	}
	return _u
}

// AddRefereeID adds value to the "referee_id" field.
func (_u *ReferralAccrualUpdateOne) AddRefereeID(v int) *ReferralAccrualUpdateOne {
	_u.mutation.AddRefereeID(v)
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *ReferralAccrualUpdateOne) SetPaymentID(v int) *ReferralAccrualUpdateOne {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillablePaymentID(v *int) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// SetPercent sets the "percent" field.
func (_u *ReferralAccrualUpdateOne) SetPercent(v float64) *ReferralAccrualUpdateOne {
	_u.mutation.ResetPercent()
	_u.mutation.SetPercent(v)
	return _u
}

// SetNillablePercent sets the "percent" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillablePercent(v *float64) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetPercent(*v)
	}
	return _u
}

// AddPercent adds value to the "percent" field.
func (_u *ReferralAccrualUpdateOne) AddPercent(v float64) *ReferralAccrualUpdateOne {
	_u.mutation.AddPercent(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralAccrualUpdateOne) SetAmount(v int64) *ReferralAccrualUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillableAmount(v *int64) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralAccrualUpdateOne) AddAmount(v int64) *ReferralAccrualUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *ReferralAccrualUpdateOne) SetDate(v time.Time) *ReferralAccrualUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillableDate(v *time.Time) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralAccrualUpdateOne) SetStatus(v referralaccrual.Status) *ReferralAccrualUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralAccrualUpdateOne) SetNillableStatus(v *referralaccrual.Status) *ReferralAccrualUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayment sets the "payment" edge to the Payment entity.
func (_u *ReferralAccrualUpdateOne) SetPayment(v *Payment) *ReferralAccrualUpdateOne {
	return _u.SetPaymentID(v.ID)
}

// Mutation returns the ReferralAccrualMutation object of the builder.
func (_u *ReferralAccrualUpdateOne) Mutation() *ReferralAccrualMutation {
	return _u.mutation
}

// ClearPayment clears the "payment" edge to the Payment entity.
func (_u *ReferralAccrualUpdateOne) ClearPayment() *ReferralAccrualUpdateOne {
	_u.mutation.ClearPayment()
	return _u
}

// Where appends a list predicates to the ReferralAccrualUpdate builder.
func (_u *ReferralAccrualUpdateOne) Where(ps ...predicate.ReferralAccrual) *ReferralAccrualUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralAccrualUpdateOne) Select(field string, fields ...string) *ReferralAccrualUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralAccrual entity.
func (_u *ReferralAccrualUpdateOne) Save(ctx context.Context) (*ReferralAccrual, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralAccrualUpdateOne) SaveX(ctx context.Context) *ReferralAccrual {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralAccrualUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralAccrualUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralAccrualUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralaccrual.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralAccrualUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := referralaccrual.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralAccrual.status": %w`, err)}
		}
	}
	if _u.mutation.PaymentCleared() && len(_u.mutation.PaymentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralAccrual.payment"`)
	}
	return nil
}

func (_u *ReferralAccrualUpdateOne) sqlSave(ctx context.Context) (_node *ReferralAccrual, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralaccrual.Table, referralaccrual.Columns, sqlgraph.NewFieldSpec(referralaccrual.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralAccrual.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralaccrual.FieldID)
		for _, f := range fields {
			if !referralaccrual.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralaccrual.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralaccrual.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReferrerID(); ok {
		_spec.SetField(referralaccrual.FieldReferrerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferrerID(); ok {
		_spec.AddField(referralaccrual.FieldReferrerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefereeID(); ok {
		_spec.SetField(referralaccrual.FieldRefereeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefereeID(); ok {
		_spec.AddField(referralaccrual.FieldRefereeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Percent(); ok {
		_spec.SetField(referralaccrual.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercent(); ok {
		_spec.AddField(referralaccrual.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralaccrual.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralaccrual.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(referralaccrual.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralaccrual.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PaymentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralaccrual.PaymentTable,
			Columns: []string{referralaccrual.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralaccrual.PaymentTable,
			Columns: []string{referralaccrual.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReferralAccrual{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralaccrual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
