// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"vpn-control/ent/payment"
	"vpn-control/ent/referralaccrual"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ReferralAccrual is the model entity for the ReferralAccrual schema.
type ReferralAccrual struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ReferrerID holds the value of the "referrer_id" field.
	ReferrerID int `json:"referrer_id,omitempty"`
	// RefereeID holds the value of the "referee_id" field.
	RefereeID int `json:"referee_id,omitempty"`
	// PaymentID holds the value of the "payment_id" field.
	PaymentID int `json:"payment_id,omitempty"`
	// Percent holds the value of the "percent" field.
	Percent float64 `json:"percent,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Status holds the value of the "status" field.
	Status referralaccrual.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralAccrualQuery when eager-loading is set.
	Edges        ReferralAccrualEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralAccrualEdges holds the relations/edges for other nodes in the graph.
type ReferralAccrualEdges struct {
	// Payment holds the value of the payment edge.
	Payment *Payment `json:"payment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentOrErr returns the Payment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralAccrualEdges) PaymentOrErr() (*Payment, error) {
	if e.Payment != nil {
		return e.Payment, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: payment.Label}
	}
	return nil, &NotLoadedError{edge: "payment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralAccrual) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralaccrual.FieldPercent:
			values[i] = new(sql.NullFloat64)
		case referralaccrual.FieldID, referralaccrual.FieldReferrerID, referralaccrual.FieldRefereeID, referralaccrual.FieldPaymentID, referralaccrual.FieldAmount:
			values[i] = new(sql.NullInt64)
		case referralaccrual.FieldStatus:
			values[i] = new(sql.NullString)
		case referralaccrual.FieldCreatedAt, referralaccrual.FieldUpdatedAt, referralaccrual.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralAccrual fields.
func (_m *ReferralAccrual) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralaccrual.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case referralaccrual.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case referralaccrual.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case referralaccrual.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = int(value.Int64)
			}
		case referralaccrual.FieldRefereeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referee_id", values[i])
			} else if value.Valid {
				_m.RefereeID = int(value.Int64)
			}
		case referralaccrual.FieldPaymentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_id", values[i])
			} else if value.Valid {
				_m.PaymentID = int(value.Int64)
			}
		case referralaccrual.FieldPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field percent", values[i])
			} else if value.Valid {
				_m.Percent = value.Float64
			}
		case referralaccrual.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case referralaccrual.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case referralaccrual.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = referralaccrual.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralAccrual.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralAccrual) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPayment queries the "payment" edge of the ReferralAccrual entity.
func (_m *ReferralAccrual) QueryPayment() *PaymentQuery {
	return NewReferralAccrualClient(_m.config).QueryPayment(_m)
}

// Update returns a builder for updating this ReferralAccrual.
// Note that you need to call ReferralAccrual.Unwrap() before calling this method if this ReferralAccrual
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralAccrual) Update() *ReferralAccrualUpdateOne {
	return NewReferralAccrualClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralAccrual entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralAccrual) Unwrap() *ReferralAccrual {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralAccrual is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralAccrual) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralAccrual(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("referee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefereeID))
	builder.WriteString(", ")
	builder.WriteString("payment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentID))
	builder.WriteString(", ")
	builder.WriteString("percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.Percent))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralAccruals is a parsable slice of ReferralAccrual.
type ReferralAccruals []*ReferralAccrual
