// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/predicate"
	"vpn-control/ent/rwuser"
	"vpn-control/ent/subscription"
	"vpn-control/ent/subscriptionaddon"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RwUserUpdate is the builder for updating RwUser entities.
type RwUserUpdate struct {
	config
	hooks    []Hook
	mutation *RwUserMutation
}

// Where appends a list predicates to the RwUserUpdate builder.
func (_u *RwUserUpdate) Where(ps ...predicate.RwUser) *RwUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *RwUserUpdate) SetUsername(v string) *RwUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableUsername(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetShortUUID sets the "short_uuid" field.
func (_u *RwUserUpdate) SetShortUUID(v string) *RwUserUpdate {
	_u.mutation.SetShortUUID(v)
	return _u
}

// SetNillableShortUUID sets the "short_uuid" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableShortUUID(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetShortUUID(*v)
	}
	return _u
}

// ClearShortUUID clears the value of the "short_uuid" field.
func (_u *RwUserUpdate) ClearShortUUID() *RwUserUpdate {
	_u.mutation.ClearShortUUID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RwUserUpdate) SetStatus(v string) *RwUserUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableStatus(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *RwUserUpdate) ClearStatus() *RwUserUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetExpireAt sets the "expire_at" field.
func (_u *RwUserUpdate) SetExpireAt(v time.Time) *RwUserUpdate {
	_u.mutation.SetExpireAt(v)
	return _u
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableExpireAt(v *time.Time) *RwUserUpdate {
	if v != nil {
		_u.SetExpireAt(*v)
	}
	return _u
}

// ClearExpireAt clears the value of the "expire_at" field.
func (_u *RwUserUpdate) ClearExpireAt() *RwUserUpdate {
	_u.mutation.ClearExpireAt()
	return _u
}

// SetUsedTrafficBytes sets the "used_traffic_bytes" field.
func (_u *RwUserUpdate) SetUsedTrafficBytes(v int64) *RwUserUpdate {
	_u.mutation.ResetUsedTrafficBytes()
	_u.mutation.SetUsedTrafficBytes(v)
	return _u
}

// SetNillableUsedTrafficBytes sets the "used_traffic_bytes" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableUsedTrafficBytes(v *int64) *RwUserUpdate {
	if v != nil {
		_u.SetUsedTrafficBytes(*v)
	}
	return _u
}

// AddUsedTrafficBytes adds value to the "used_traffic_bytes" field.
func (_u *RwUserUpdate) AddUsedTrafficBytes(v int64) *RwUserUpdate {
	_u.mutation.AddUsedTrafficBytes(v)
	return _u
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (_u *RwUserUpdate) SetTrafficLimitBytes(v int64) *RwUserUpdate {
	_u.mutation.ResetTrafficLimitBytes()
	_u.mutation.SetTrafficLimitBytes(v)
	return _u
}

// SetNillableTrafficLimitBytes sets the "traffic_limit_bytes" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableTrafficLimitBytes(v *int64) *RwUserUpdate {
	if v != nil {
		_u.SetTrafficLimitBytes(*v)
	}
	return _u
}

// AddTrafficLimitBytes adds value to the "traffic_limit_bytes" field.
func (_u *RwUserUpdate) AddTrafficLimitBytes(v int64) *RwUserUpdate {
	_u.mutation.AddTrafficLimitBytes(v)
	return _u
}

// SetTrafficLimitStrategy sets the "traffic_limit_strategy" field.
func (_u *RwUserUpdate) SetTrafficLimitStrategy(v string) *RwUserUpdate {
	_u.mutation.SetTrafficLimitStrategy(v)
	return _u
}

// SetNillableTrafficLimitStrategy sets the "traffic_limit_strategy" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableTrafficLimitStrategy(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetTrafficLimitStrategy(*v)
	}
	return _u
}

// ClearTrafficLimitStrategy clears the value of the "traffic_limit_strategy" field.
func (_u *RwUserUpdate) ClearTrafficLimitStrategy() *RwUserUpdate {
	_u.mutation.ClearTrafficLimitStrategy()
	return _u
}

// SetLastTrafficResetAt sets the "last_traffic_reset_at" field.
func (_u *RwUserUpdate) SetLastTrafficResetAt(v time.Time) *RwUserUpdate {
	_u.mutation.SetLastTrafficResetAt(v)
	return _u
}

// SetNillableLastTrafficResetAt sets the "last_traffic_reset_at" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableLastTrafficResetAt(v *time.Time) *RwUserUpdate {
	if v != nil {
		_u.SetLastTrafficResetAt(*v)
	}
	return _u
}

// ClearLastTrafficResetAt clears the value of the "last_traffic_reset_at" field.
func (_u *RwUserUpdate) ClearLastTrafficResetAt() *RwUserUpdate {
	_u.mutation.ClearLastTrafficResetAt()
	return _u
}

// SetPanelCreatedAt sets the "panel_created_at" field.
func (_u *RwUserUpdate) SetPanelCreatedAt(v time.Time) *RwUserUpdate {
	_u.mutation.SetPanelCreatedAt(v)
	return _u
}

// SetNillablePanelCreatedAt sets the "panel_created_at" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillablePanelCreatedAt(v *time.Time) *RwUserUpdate {
	if v != nil {
		_u.SetPanelCreatedAt(*v)
	}
	return _u
}

// ClearPanelCreatedAt clears the value of the "panel_created_at" field.
func (_u *RwUserUpdate) ClearPanelCreatedAt() *RwUserUpdate {
	_u.mutation.ClearPanelCreatedAt()
	return _u
}

// SetHwidDeviceLimit sets the "hwid_device_limit" field.
func (_u *RwUserUpdate) SetHwidDeviceLimit(v int) *RwUserUpdate {
	_u.mutation.ResetHwidDeviceLimit()
	_u.mutation.SetHwidDeviceLimit(v)
	return _u
}

// SetNillableHwidDeviceLimit sets the "hwid_device_limit" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableHwidDeviceLimit(v *int) *RwUserUpdate {
	if v != nil {
		_u.SetHwidDeviceLimit(*v)
	}
	return _u
}

// AddHwidDeviceLimit adds value to the "hwid_device_limit" field.
func (_u *RwUserUpdate) AddHwidDeviceLimit(v int) *RwUserUpdate {
	_u.mutation.AddHwidDeviceLimit(v)
	return _u
}

// ClearHwidDeviceLimit clears the value of the "hwid_device_limit" field.
func (_u *RwUserUpdate) ClearHwidDeviceLimit() *RwUserUpdate {
	_u.mutation.ClearHwidDeviceLimit()
	return _u
}

// SetOnlineAt sets the "online_at" field.
func (_u *RwUserUpdate) SetOnlineAt(v time.Time) *RwUserUpdate {
	_u.mutation.SetOnlineAt(v)
	return _u
}

// SetNillableOnlineAt sets the "online_at" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableOnlineAt(v *time.Time) *RwUserUpdate {
	if v != nil {
		_u.SetOnlineAt(*v)
	}
	return _u
}

// ClearOnlineAt clears the value of the "online_at" field.
func (_u *RwUserUpdate) ClearOnlineAt() *RwUserUpdate {
	_u.mutation.ClearOnlineAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RwUserUpdate) SetDescription(v string) *RwUserUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableDescription(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RwUserUpdate) ClearDescription() *RwUserUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTag sets the "tag" field.
func (_u *RwUserUpdate) SetTag(v string) *RwUserUpdate {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableTag(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *RwUserUpdate) ClearTag() *RwUserUpdate {
	_u.mutation.ClearTag()
	return _u
}

// SetTelegramID sets the "telegram_id" field.
func (_u *RwUserUpdate) SetTelegramID(v int64) *RwUserUpdate {
	_u.mutation.ResetTelegramID()
	_u.mutation.SetTelegramID(v)
	return _u
}

// SetNillableTelegramID sets the "telegram_id" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableTelegramID(v *int64) *RwUserUpdate {
	if v != nil {
		_u.SetTelegramID(*v)
	}
	return _u
}

// AddTelegramID adds value to the "telegram_id" field.
func (_u *RwUserUpdate) AddTelegramID(v int64) *RwUserUpdate {
	_u.mutation.AddTelegramID(v)
	return _u
}

// ClearTelegramID clears the value of the "telegram_id" field.
func (_u *RwUserUpdate) ClearTelegramID() *RwUserUpdate {
	_u.mutation.ClearTelegramID()
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *RwUserUpdate) SetSubscriptionURL(v string) *RwUserUpdate {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableSubscriptionURL(v *string) *RwUserUpdate {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (_u *RwUserUpdate) ClearSubscriptionURL() *RwUserUpdate {
	_u.mutation.ClearSubscriptionURL()
	return _u
}

// SetSquadUuids sets the "squad_uuids" field.
func (_u *RwUserUpdate) SetSquadUuids(v []string) *RwUserUpdate {
	_u.mutation.SetSquadUuids(v)
	return _u
}

// AppendSquadUuids appends value to the "squad_uuids" field.
func (_u *RwUserUpdate) AppendSquadUuids(v []string) *RwUserUpdate {
	_u.mutation.AppendSquadUuids(v)
	return _u
}

// ClearSquadUuids clears the value of the "squad_uuids" field.
func (_u *RwUserUpdate) ClearSquadUuids() *RwUserUpdate {
	_u.mutation.ClearSquadUuids()
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *RwUserUpdate) SetDeleted(v bool) *RwUserUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableDeleted(v *bool) *RwUserUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RwUserUpdate) SetSyncedAt(v time.Time) *RwUserUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RwUserUpdate) SetNillableSyncedAt(v *time.Time) *RwUserUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (_u *RwUserUpdate) SetSubscriptionID(id int) *RwUserUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetNillableSubscriptionID sets the "subscription" edge to the Subscription entity by ID if the given value is not nil.
func (_u *RwUserUpdate) SetNillableSubscriptionID(id *int) *RwUserUpdate {
	if id != nil {
		_u = _u.SetSubscriptionID(*id)
	}
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *RwUserUpdate) SetSubscription(v *Subscription) *RwUserUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetSubscriptionAddonID sets the "subscription_addon" edge to the SubscriptionAddon entity by ID.
func (_u *RwUserUpdate) SetSubscriptionAddonID(id int) *RwUserUpdate {
	_u.mutation.SetSubscriptionAddonID(id)
	return _u
}

// SetNillableSubscriptionAddonID sets the "subscription_addon" edge to the SubscriptionAddon entity by ID if the given value is not nil.
func (_u *RwUserUpdate) SetNillableSubscriptionAddonID(id *int) *RwUserUpdate {
	if id != nil {
		_u = _u.SetSubscriptionAddonID(*id)
	}
	return _u
}

// SetSubscriptionAddon sets the "subscription_addon" edge to the SubscriptionAddon entity.
func (_u *RwUserUpdate) SetSubscriptionAddon(v *SubscriptionAddon) *RwUserUpdate {
	return _u.SetSubscriptionAddonID(v.ID)
}

// Mutation returns the RwUserMutation object of the builder.
func (_u *RwUserUpdate) Mutation() *RwUserMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *RwUserUpdate) ClearSubscription() *RwUserUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearSubscriptionAddon clears the "subscription_addon" edge to the SubscriptionAddon entity.
func (_u *RwUserUpdate) ClearSubscriptionAddon() *RwUserUpdate {
	_u.mutation.ClearSubscriptionAddon()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RwUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RwUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RwUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RwUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RwUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rwuser.Table, rwuser.Columns, sqlgraph.NewFieldSpec(rwuser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(rwuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortUUID(); ok {
		_spec.SetField(rwuser.FieldShortUUID, field.TypeString, value)
	}
	if _u.mutation.ShortUUIDCleared() {
		_spec.ClearField(rwuser.FieldShortUUID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rwuser.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(rwuser.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ExpireAt(); ok {
		_spec.SetField(rwuser.FieldExpireAt, field.TypeTime, value)
	}
	if _u.mutation.ExpireAtCleared() {
		_spec.ClearField(rwuser.FieldExpireAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedTrafficBytes(); ok {
		_spec.SetField(rwuser.FieldUsedTrafficBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedTrafficBytes(); ok {
		_spec.AddField(rwuser.FieldUsedTrafficBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficLimitBytes(); ok {
		_spec.SetField(rwuser.FieldTrafficLimitBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTrafficLimitBytes(); ok {
		_spec.AddField(rwuser.FieldTrafficLimitBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficLimitStrategy(); ok {
		_spec.SetField(rwuser.FieldTrafficLimitStrategy, field.TypeString, value)
	}
	if _u.mutation.TrafficLimitStrategyCleared() {
		_spec.ClearField(rwuser.FieldTrafficLimitStrategy, field.TypeString)
	}
	if value, ok := _u.mutation.LastTrafficResetAt(); ok {
		_spec.SetField(rwuser.FieldLastTrafficResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastTrafficResetAtCleared() {
		_spec.ClearField(rwuser.FieldLastTrafficResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PanelCreatedAt(); ok {
		_spec.SetField(rwuser.FieldPanelCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PanelCreatedAtCleared() {
		_spec.ClearField(rwuser.FieldPanelCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HwidDeviceLimit(); ok {
		_spec.SetField(rwuser.FieldHwidDeviceLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHwidDeviceLimit(); ok {
		_spec.AddField(rwuser.FieldHwidDeviceLimit, field.TypeInt, value)
	}
	if _u.mutation.HwidDeviceLimitCleared() {
		_spec.ClearField(rwuser.FieldHwidDeviceLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.OnlineAt(); ok {
		_spec.SetField(rwuser.FieldOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.OnlineAtCleared() {
		_spec.ClearField(rwuser.FieldOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rwuser.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rwuser.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(rwuser.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(rwuser.FieldTag, field.TypeString)
	}
	if value, ok := _u.mutation.TelegramID(); ok {
		_spec.SetField(rwuser.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramID(); ok {
		_spec.AddField(rwuser.FieldTelegramID, field.TypeInt64, value)
	}
	if _u.mutation.TelegramIDCleared() {
		_spec.ClearField(rwuser.FieldTelegramID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(rwuser.FieldSubscriptionURL, field.TypeString, value)
	}
	if _u.mutation.SubscriptionURLCleared() {
		_spec.ClearField(rwuser.FieldSubscriptionURL, field.TypeString)
	}
	if value, ok := _u.mutation.SquadUuids(); ok {
		_spec.SetField(rwuser.FieldSquadUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSquadUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rwuser.FieldSquadUuids, value)
		})
	}
	if _u.mutation.SquadUuidsCleared() {
		_spec.ClearField(rwuser.FieldSquadUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(rwuser.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(rwuser.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionTable,
			Columns: []string{rwuser.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionTable,
			Columns: []string{rwuser.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionAddonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionAddonTable,
			Columns: []string{rwuser.SubscriptionAddonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionaddon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionAddonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionAddonTable,
			Columns: []string{rwuser.SubscriptionAddonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionaddon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rwuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RwUserUpdateOne is the builder for updating a single RwUser entity.
type RwUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RwUserMutation
}

// SetUsername sets the "username" field.
func (_u *RwUserUpdateOne) SetUsername(v string) *RwUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableUsername(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetShortUUID sets the "short_uuid" field.
func (_u *RwUserUpdateOne) SetShortUUID(v string) *RwUserUpdateOne {
	_u.mutation.SetShortUUID(v)
	return _u
}

// SetNillableShortUUID sets the "short_uuid" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableShortUUID(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetShortUUID(*v)
	}
	return _u
}

// ClearShortUUID clears the value of the "short_uuid" field.
func (_u *RwUserUpdateOne) ClearShortUUID() *RwUserUpdateOne {
	_u.mutation.ClearShortUUID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RwUserUpdateOne) SetStatus(v string) *RwUserUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableStatus(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *RwUserUpdateOne) ClearStatus() *RwUserUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetExpireAt sets the "expire_at" field.
func (_u *RwUserUpdateOne) SetExpireAt(v time.Time) *RwUserUpdateOne {
	_u.mutation.SetExpireAt(v)
	return _u
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableExpireAt(v *time.Time) *RwUserUpdateOne {
	if v != nil {
		_u.SetExpireAt(*v)
	}
	return _u
}

// ClearExpireAt clears the value of the "expire_at" field.
func (_u *RwUserUpdateOne) ClearExpireAt() *RwUserUpdateOne {
	_u.mutation.ClearExpireAt()
	return _u
}

// SetUsedTrafficBytes sets the "used_traffic_bytes" field.
func (_u *RwUserUpdateOne) SetUsedTrafficBytes(v int64) *RwUserUpdateOne {
	_u.mutation.ResetUsedTrafficBytes()
	_u.mutation.SetUsedTrafficBytes(v)
	return _u
}

// SetNillableUsedTrafficBytes sets the "used_traffic_bytes" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableUsedTrafficBytes(v *int64) *RwUserUpdateOne {
	if v != nil {
		_u.SetUsedTrafficBytes(*v)
	}
	return _u
}

// AddUsedTrafficBytes adds value to the "used_traffic_bytes" field.
func (_u *RwUserUpdateOne) AddUsedTrafficBytes(v int64) *RwUserUpdateOne {
	_u.mutation.AddUsedTrafficBytes(v)
	return _u
}

// SetTrafficLimitBytes sets the "traffic_limit_bytes" field.
func (_u *RwUserUpdateOne) SetTrafficLimitBytes(v int64) *RwUserUpdateOne {
	_u.mutation.ResetTrafficLimitBytes()
	_u.mutation.SetTrafficLimitBytes(v)
	return _u
}

// SetNillableTrafficLimitBytes sets the "traffic_limit_bytes" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableTrafficLimitBytes(v *int64) *RwUserUpdateOne {
	if v != nil {
		_u.SetTrafficLimitBytes(*v)
	}
	return _u
}

// AddTrafficLimitBytes adds value to the "traffic_limit_bytes" field.
func (_u *RwUserUpdateOne) AddTrafficLimitBytes(v int64) *RwUserUpdateOne {
	_u.mutation.AddTrafficLimitBytes(v)
	return _u
}

// SetTrafficLimitStrategy sets the "traffic_limit_strategy" field.
func (_u *RwUserUpdateOne) SetTrafficLimitStrategy(v string) *RwUserUpdateOne {
	_u.mutation.SetTrafficLimitStrategy(v)
	return _u
}

// SetNillableTrafficLimitStrategy sets the "traffic_limit_strategy" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableTrafficLimitStrategy(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetTrafficLimitStrategy(*v)
	}
	return _u
}

// ClearTrafficLimitStrategy clears the value of the "traffic_limit_strategy" field.
func (_u *RwUserUpdateOne) ClearTrafficLimitStrategy() *RwUserUpdateOne {
	_u.mutation.ClearTrafficLimitStrategy()
	return _u
}

// SetLastTrafficResetAt sets the "last_traffic_reset_at" field.
func (_u *RwUserUpdateOne) SetLastTrafficResetAt(v time.Time) *RwUserUpdateOne {
	_u.mutation.SetLastTrafficResetAt(v)
	return _u
}

// SetNillableLastTrafficResetAt sets the "last_traffic_reset_at" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableLastTrafficResetAt(v *time.Time) *RwUserUpdateOne {
	if v != nil {
		_u.SetLastTrafficResetAt(*v)
	}
	return _u
}

// ClearLastTrafficResetAt clears the value of the "last_traffic_reset_at" field.
func (_u *RwUserUpdateOne) ClearLastTrafficResetAt() *RwUserUpdateOne {
	_u.mutation.ClearLastTrafficResetAt()
	return _u
}

// SetPanelCreatedAt sets the "panel_created_at" field.
func (_u *RwUserUpdateOne) SetPanelCreatedAt(v time.Time) *RwUserUpdateOne {
	_u.mutation.SetPanelCreatedAt(v)
	return _u
}

// SetNillablePanelCreatedAt sets the "panel_created_at" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillablePanelCreatedAt(v *time.Time) *RwUserUpdateOne {
	if v != nil {
		_u.SetPanelCreatedAt(*v)
	}
	return _u
}

// ClearPanelCreatedAt clears the value of the "panel_created_at" field.
func (_u *RwUserUpdateOne) ClearPanelCreatedAt() *RwUserUpdateOne {
	_u.mutation.ClearPanelCreatedAt()
	return _u
}

// SetHwidDeviceLimit sets the "hwid_device_limit" field.
func (_u *RwUserUpdateOne) SetHwidDeviceLimit(v int) *RwUserUpdateOne {
	_u.mutation.ResetHwidDeviceLimit()
	_u.mutation.SetHwidDeviceLimit(v)
	return _u
}

// SetNillableHwidDeviceLimit sets the "hwid_device_limit" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableHwidDeviceLimit(v *int) *RwUserUpdateOne {
	if v != nil {
		_u.SetHwidDeviceLimit(*v)
	}
	return _u
}

// AddHwidDeviceLimit adds value to the "hwid_device_limit" field.
func (_u *RwUserUpdateOne) AddHwidDeviceLimit(v int) *RwUserUpdateOne {
	_u.mutation.AddHwidDeviceLimit(v)
	return _u
}

// ClearHwidDeviceLimit clears the value of the "hwid_device_limit" field.
func (_u *RwUserUpdateOne) ClearHwidDeviceLimit() *RwUserUpdateOne {
	_u.mutation.ClearHwidDeviceLimit()
	return _u
}

// SetOnlineAt sets the "online_at" field.
func (_u *RwUserUpdateOne) SetOnlineAt(v time.Time) *RwUserUpdateOne {
	_u.mutation.SetOnlineAt(v)
	return _u
}

// SetNillableOnlineAt sets the "online_at" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableOnlineAt(v *time.Time) *RwUserUpdateOne {
	if v != nil {
		_u.SetOnlineAt(*v)
	}
	return _u
}

// ClearOnlineAt clears the value of the "online_at" field.
func (_u *RwUserUpdateOne) ClearOnlineAt() *RwUserUpdateOne {
	_u.mutation.ClearOnlineAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RwUserUpdateOne) SetDescription(v string) *RwUserUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableDescription(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RwUserUpdateOne) ClearDescription() *RwUserUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTag sets the "tag" field.
func (_u *RwUserUpdateOne) SetTag(v string) *RwUserUpdateOne {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableTag(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *RwUserUpdateOne) ClearTag() *RwUserUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// SetTelegramID sets the "telegram_id" field.
func (_u *RwUserUpdateOne) SetTelegramID(v int64) *RwUserUpdateOne {
	_u.mutation.ResetTelegramID()
	_u.mutation.SetTelegramID(v)
	return _u
}

// SetNillableTelegramID sets the "telegram_id" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableTelegramID(v *int64) *RwUserUpdateOne {
	if v != nil {
		_u.SetTelegramID(*v)
	}
	return _u
}

// AddTelegramID adds value to the "telegram_id" field.
func (_u *RwUserUpdateOne) AddTelegramID(v int64) *RwUserUpdateOne {
	_u.mutation.AddTelegramID(v)
	return _u
}

// ClearTelegramID clears the value of the "telegram_id" field.
func (_u *RwUserUpdateOne) ClearTelegramID() *RwUserUpdateOne {
	_u.mutation.ClearTelegramID()
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *RwUserUpdateOne) SetSubscriptionURL(v string) *RwUserUpdateOne {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableSubscriptionURL(v *string) *RwUserUpdateOne {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (_u *RwUserUpdateOne) ClearSubscriptionURL() *RwUserUpdateOne {
	_u.mutation.ClearSubscriptionURL()
	return _u
}

// SetSquadUuids sets the "squad_uuids" field.
func (_u *RwUserUpdateOne) SetSquadUuids(v []string) *RwUserUpdateOne {
	_u.mutation.SetSquadUuids(v)
	return _u
}

// AppendSquadUuids appends value to the "squad_uuids" field.
func (_u *RwUserUpdateOne) AppendSquadUuids(v []string) *RwUserUpdateOne {
	_u.mutation.AppendSquadUuids(v)
	return _u
}

// ClearSquadUuids clears the value of the "squad_uuids" field.
func (_u *RwUserUpdateOne) ClearSquadUuids() *RwUserUpdateOne {
	_u.mutation.ClearSquadUuids()
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *RwUserUpdateOne) SetDeleted(v bool) *RwUserUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableDeleted(v *bool) *RwUserUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RwUserUpdateOne) SetSyncedAt(v time.Time) *RwUserUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableSyncedAt(v *time.Time) *RwUserUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (_u *RwUserUpdateOne) SetSubscriptionID(id int) *RwUserUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetNillableSubscriptionID sets the "subscription" edge to the Subscription entity by ID if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableSubscriptionID(id *int) *RwUserUpdateOne {
	if id != nil {
		_u = _u.SetSubscriptionID(*id)
	}
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *RwUserUpdateOne) SetSubscription(v *Subscription) *RwUserUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetSubscriptionAddonID sets the "subscription_addon" edge to the SubscriptionAddon entity by ID.
func (_u *RwUserUpdateOne) SetSubscriptionAddonID(id int) *RwUserUpdateOne {
	_u.mutation.SetSubscriptionAddonID(id)
	return _u
}

// SetNillableSubscriptionAddonID sets the "subscription_addon" edge to the SubscriptionAddon entity by ID if the given value is not nil.
func (_u *RwUserUpdateOne) SetNillableSubscriptionAddonID(id *int) *RwUserUpdateOne {
	if id != nil {
		_u = _u.SetSubscriptionAddonID(*id)
	}
	return _u
}

// SetSubscriptionAddon sets the "subscription_addon" edge to the SubscriptionAddon entity.
func (_u *RwUserUpdateOne) SetSubscriptionAddon(v *SubscriptionAddon) *RwUserUpdateOne {
	return _u.SetSubscriptionAddonID(v.ID)
}

// Mutation returns the RwUserMutation object of the builder.
func (_u *RwUserUpdateOne) Mutation() *RwUserMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *RwUserUpdateOne) ClearSubscription() *RwUserUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearSubscriptionAddon clears the "subscription_addon" edge to the SubscriptionAddon entity.
func (_u *RwUserUpdateOne) ClearSubscriptionAddon() *RwUserUpdateOne {
	_u.mutation.ClearSubscriptionAddon()
	return _u
}

// Where appends a list predicates to the RwUserUpdate builder.
func (_u *RwUserUpdateOne) Where(ps ...predicate.RwUser) *RwUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RwUserUpdateOne) Select(field string, fields ...string) *RwUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RwUser entity.
func (_u *RwUserUpdateOne) Save(ctx context.Context) (*RwUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RwUserUpdateOne) SaveX(ctx context.Context) *RwUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RwUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RwUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RwUserUpdateOne) sqlSave(ctx context.Context) (_node *RwUser, err error) {
	_spec := sqlgraph.NewUpdateSpec(rwuser.Table, rwuser.Columns, sqlgraph.NewFieldSpec(rwuser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RwUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rwuser.FieldID)
		for _, f := range fields {
			if !rwuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rwuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(rwuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortUUID(); ok {
		_spec.SetField(rwuser.FieldShortUUID, field.TypeString, value)
	}
	if _u.mutation.ShortUUIDCleared() {
		_spec.ClearField(rwuser.FieldShortUUID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rwuser.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(rwuser.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ExpireAt(); ok {
		_spec.SetField(rwuser.FieldExpireAt, field.TypeTime, value)
	}
	if _u.mutation.ExpireAtCleared() {
		_spec.ClearField(rwuser.FieldExpireAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedTrafficBytes(); ok {
		_spec.SetField(rwuser.FieldUsedTrafficBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedTrafficBytes(); ok {
		_spec.AddField(rwuser.FieldUsedTrafficBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficLimitBytes(); ok {
		_spec.SetField(rwuser.FieldTrafficLimitBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTrafficLimitBytes(); ok {
		_spec.AddField(rwuser.FieldTrafficLimitBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficLimitStrategy(); ok {
		_spec.SetField(rwuser.FieldTrafficLimitStrategy, field.TypeString, value)
	}
	if _u.mutation.TrafficLimitStrategyCleared() {
		_spec.ClearField(rwuser.FieldTrafficLimitStrategy, field.TypeString)
	}
	if value, ok := _u.mutation.LastTrafficResetAt(); ok {
		_spec.SetField(rwuser.FieldLastTrafficResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastTrafficResetAtCleared() {
		_spec.ClearField(rwuser.FieldLastTrafficResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PanelCreatedAt(); ok {
		_spec.SetField(rwuser.FieldPanelCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PanelCreatedAtCleared() {
		_spec.ClearField(rwuser.FieldPanelCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HwidDeviceLimit(); ok {
		_spec.SetField(rwuser.FieldHwidDeviceLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHwidDeviceLimit(); ok {
		_spec.AddField(rwuser.FieldHwidDeviceLimit, field.TypeInt, value)
	}
	if _u.mutation.HwidDeviceLimitCleared() {
		_spec.ClearField(rwuser.FieldHwidDeviceLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.OnlineAt(); ok {
		_spec.SetField(rwuser.FieldOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.OnlineAtCleared() {
		_spec.ClearField(rwuser.FieldOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rwuser.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rwuser.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(rwuser.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(rwuser.FieldTag, field.TypeString)
	}
	if value, ok := _u.mutation.TelegramID(); ok {
		_spec.SetField(rwuser.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramID(); ok {
		_spec.AddField(rwuser.FieldTelegramID, field.TypeInt64, value)
	}
	if _u.mutation.TelegramIDCleared() {
		_spec.ClearField(rwuser.FieldTelegramID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(rwuser.FieldSubscriptionURL, field.TypeString, value)
	}
	if _u.mutation.SubscriptionURLCleared() {
		_spec.ClearField(rwuser.FieldSubscriptionURL, field.TypeString)
	}
	if value, ok := _u.mutation.SquadUuids(); ok {
		_spec.SetField(rwuser.FieldSquadUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSquadUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rwuser.FieldSquadUuids, value)
		})
	}
	if _u.mutation.SquadUuidsCleared() {
		_spec.ClearField(rwuser.FieldSquadUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(rwuser.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(rwuser.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionTable,
			Columns: []string{rwuser.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionTable,
			Columns: []string{rwuser.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionAddonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionAddonTable,
			Columns: []string{rwuser.SubscriptionAddonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionaddon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionAddonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rwuser.SubscriptionAddonTable,
			Columns: []string{rwuser.SubscriptionAddonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionaddon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RwUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rwuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
