// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"vpn-control/ent/predicate"
	"vpn-control/ent/tariff"
	"vpn-control/ent/tariffperiod"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TariffPeriodUpdate is the builder for updating TariffPeriod entities.
type TariffPeriodUpdate struct {
	config
	hooks    []Hook
	mutation *TariffPeriodMutation
}

// Where appends a list predicates to the TariffPeriodUpdate builder.
func (_u *TariffPeriodUpdate) Where(ps ...predicate.TariffPeriod) *TariffPeriodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTariffID sets the "tariff_id" field.
func (_u *TariffPeriodUpdate) SetTariffID(v int) *TariffPeriodUpdate {
	_u.mutation.SetTariffID(v)
	return _u
}

// SetNillableTariffID sets the "tariff_id" field if the given value is not nil.
func (_u *TariffPeriodUpdate) SetNillableTariffID(v *int) *TariffPeriodUpdate {
	if v != nil {
		_u.SetTariffID(*v)
	}
	return _u
}

// SetMonths sets the "months" field.
func (_u *TariffPeriodUpdate) SetMonths(v int) *TariffPeriodUpdate {
	_u.mutation.ResetMonths()
	_u.mutation.SetMonths(v)
	return _u
}

// SetNillableMonths sets the "months" field if the given value is not nil.
func (_u *TariffPeriodUpdate) SetNillableMonths(v *int) *TariffPeriodUpdate {
	if v != nil {
		_u.SetMonths(*v)
	}
	return _u
}

// AddMonths adds value to the "months" field.
func (_u *TariffPeriodUpdate) AddMonths(v int) *TariffPeriodUpdate {
	_u.mutation.AddMonths(v)
	return _u
}

// SetDays sets the "days" field.
func (_u *TariffPeriodUpdate) SetDays(v int) *TariffPeriodUpdate {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *TariffPeriodUpdate) SetNillableDays(v *int) *TariffPeriodUpdate {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *TariffPeriodUpdate) AddDays(v int) *TariffPeriodUpdate {
	_u.mutation.AddDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *TariffPeriodUpdate) SetPrice(v int64) *TariffPeriodUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *TariffPeriodUpdate) SetNillablePrice(v *int64) *TariffPeriodUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *TariffPeriodUpdate) AddPrice(v int64) *TariffPeriodUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetTariff sets the "tariff" edge to the Tariff entity.
func (_u *TariffPeriodUpdate) SetTariff(v *Tariff) *TariffPeriodUpdate {
	return _u.SetTariffID(v.ID)
}

// Mutation returns the TariffPeriodMutation object of the builder.
func (_u *TariffPeriodUpdate) Mutation() *TariffPeriodMutation {
	return _u.mutation
}

// ClearTariff clears the "tariff" edge to the Tariff entity.
func (_u *TariffPeriodUpdate) ClearTariff() *TariffPeriodUpdate {
	_u.mutation.ClearTariff()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TariffPeriodUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TariffPeriodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TariffPeriodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TariffPeriodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TariffPeriodUpdate) check() error {
	if v, ok := _u.mutation.Months(); ok {
		if err := tariffperiod.MonthsValidator(v); err != nil {
			return &ValidationError{Name: "months", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.months": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Days(); ok {
		if err := tariffperiod.DaysValidator(v); err != nil {
			return &ValidationError{Name: "days", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := tariffperiod.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.price": %w`, err)}
		}
	}
	if _u.mutation.TariffCleared() && len(_u.mutation.TariffIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TariffPeriod.tariff"`)
	}
	return nil
}

func (_u *TariffPeriodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tariffperiod.Table, tariffperiod.Columns, sqlgraph.NewFieldSpec(tariffperiod.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Months(); ok {
		_spec.SetField(tariffperiod.FieldMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonths(); ok {
		_spec.AddField(tariffperiod.FieldMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(tariffperiod.FieldDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(tariffperiod.FieldDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(tariffperiod.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(tariffperiod.FieldPrice, field.TypeInt64, value)
	}
	if _u.mutation.TariffCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tariffperiod.TariffTable,
			Columns: []string{tariffperiod.TariffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tariff.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TariffIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tariffperiod.TariffTable,
			Columns: []string{tariffperiod.TariffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tariff.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tariffperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TariffPeriodUpdateOne is the builder for updating a single TariffPeriod entity.
type TariffPeriodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TariffPeriodMutation
}

// SetTariffID sets the "tariff_id" field.
func (_u *TariffPeriodUpdateOne) SetTariffID(v int) *TariffPeriodUpdateOne {
	_u.mutation.SetTariffID(v)
	return _u
}

// SetNillableTariffID sets the "tariff_id" field if the given value is not nil.
func (_u *TariffPeriodUpdateOne) SetNillableTariffID(v *int) *TariffPeriodUpdateOne {
	if v != nil {
		_u.SetTariffID(*v)
	}
	return _u
}

// SetMonths sets the "months" field.
func (_u *TariffPeriodUpdateOne) SetMonths(v int) *TariffPeriodUpdateOne {
	_u.mutation.ResetMonths()
	_u.mutation.SetMonths(v)
	return _u
}

// SetNillableMonths sets the "months" field if the given value is not nil.
func (_u *TariffPeriodUpdateOne) SetNillableMonths(v *int) *TariffPeriodUpdateOne {
	if v != nil {
		_u.SetMonths(*v)
	}
	return _u
}

// AddMonths adds value to the "months" field.
func (_u *TariffPeriodUpdateOne) AddMonths(v int) *TariffPeriodUpdateOne {
	_u.mutation.AddMonths(v)
	return _u
}

// SetDays sets the "days" field.
func (_u *TariffPeriodUpdateOne) SetDays(v int) *TariffPeriodUpdateOne {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *TariffPeriodUpdateOne) SetNillableDays(v *int) *TariffPeriodUpdateOne {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *TariffPeriodUpdateOne) AddDays(v int) *TariffPeriodUpdateOne {
	_u.mutation.AddDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *TariffPeriodUpdateOne) SetPrice(v int64) *TariffPeriodUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *TariffPeriodUpdateOne) SetNillablePrice(v *int64) *TariffPeriodUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *TariffPeriodUpdateOne) AddPrice(v int64) *TariffPeriodUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetTariff sets the "tariff" edge to the Tariff entity.
func (_u *TariffPeriodUpdateOne) SetTariff(v *Tariff) *TariffPeriodUpdateOne {
	return _u.SetTariffID(v.ID)
}

// Mutation returns the TariffPeriodMutation object of the builder.
func (_u *TariffPeriodUpdateOne) Mutation() *TariffPeriodMutation {
	return _u.mutation
}

// ClearTariff clears the "tariff" edge to the Tariff entity.
func (_u *TariffPeriodUpdateOne) ClearTariff() *TariffPeriodUpdateOne {
	_u.mutation.ClearTariff()
	return _u
}

// Where appends a list predicates to the TariffPeriodUpdate builder.
func (_u *TariffPeriodUpdateOne) Where(ps ...predicate.TariffPeriod) *TariffPeriodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TariffPeriodUpdateOne) Select(field string, fields ...string) *TariffPeriodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TariffPeriod entity.
func (_u *TariffPeriodUpdateOne) Save(ctx context.Context) (*TariffPeriod, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TariffPeriodUpdateOne) SaveX(ctx context.Context) *TariffPeriod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TariffPeriodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TariffPeriodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TariffPeriodUpdateOne) check() error {
	if v, ok := _u.mutation.Months(); ok {
		if err := tariffperiod.MonthsValidator(v); err != nil {
			return &ValidationError{Name: "months", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.months": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Days(); ok {
		if err := tariffperiod.DaysValidator(v); err != nil {
			return &ValidationError{Name: "days", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := tariffperiod.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "TariffPeriod.price": %w`, err)}
		}
	}
	if _u.mutation.TariffCleared() && len(_u.mutation.TariffIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TariffPeriod.tariff"`)
	}
	return nil
}

func (_u *TariffPeriodUpdateOne) sqlSave(ctx context.Context) (_node *TariffPeriod, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tariffperiod.Table, tariffperiod.Columns, sqlgraph.NewFieldSpec(tariffperiod.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TariffPeriod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tariffperiod.FieldID)
		for _, f := range fields {
			if !tariffperiod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tariffperiod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Months(); ok {
		_spec.SetField(tariffperiod.FieldMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonths(); ok {
		_spec.AddField(tariffperiod.FieldMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(tariffperiod.FieldDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(tariffperiod.FieldDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(tariffperiod.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(tariffperiod.FieldPrice, field.TypeInt64, value)
	}
	if _u.mutation.TariffCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tariffperiod.TariffTable,
			Columns: []string{tariffperiod.TariffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tariff.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TariffIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tariffperiod.TariffTable,
			Columns: []string{tariffperiod.TariffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tariff.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TariffPeriod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tariffperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
