// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"vpn-control/ent/predicate"
	"vpn-control/ent/trafficsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrafficSnapshotDelete is the builder for deleting a TrafficSnapshot entity.
type TrafficSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *TrafficSnapshotMutation
}

// Where appends a list predicates to the TrafficSnapshotDelete builder.
func (_d *TrafficSnapshotDelete) Where(ps ...predicate.TrafficSnapshot) *TrafficSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TrafficSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrafficSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TrafficSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trafficsnapshot.Table, sqlgraph.NewFieldSpec(trafficsnapshot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TrafficSnapshotDeleteOne is the builder for deleting a single TrafficSnapshot entity.
type TrafficSnapshotDeleteOne struct {
	_d *TrafficSnapshotDelete
}

// Where appends a list predicates to the TrafficSnapshotDelete builder.
func (_d *TrafficSnapshotDeleteOne) Where(ps ...predicate.TrafficSnapshot) *TrafficSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TrafficSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trafficsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrafficSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
