// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"vpn-control/ent/predicate"
	"vpn-control/ent/trafficsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrafficSnapshotUpdate is the builder for updating TrafficSnapshot entities.
type TrafficSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *TrafficSnapshotMutation
}

// Where appends a list predicates to the TrafficSnapshotUpdate builder.
func (_u *TrafficSnapshotUpdate) Where(ps ...predicate.TrafficSnapshot) *TrafficSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *TrafficSnapshotUpdate) SetDate(v string) *TrafficSnapshotUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TrafficSnapshotUpdate) SetNillableDate(v *string) *TrafficSnapshotUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetNodeUUID sets the "node_uuid" field.
func (_u *TrafficSnapshotUpdate) SetNodeUUID(v string) *TrafficSnapshotUpdate {
	_u.mutation.SetNodeUUID(v)
	return _u
}

// SetNillableNodeUUID sets the "node_uuid" field if the given value is not nil.
func (_u *TrafficSnapshotUpdate) SetNillableNodeUUID(v *string) *TrafficSnapshotUpdate {
	if v != nil {
		_u.SetNodeUUID(*v)
	}
	return _u
}

// SetNodeName sets the "node_name" field.
func (_u *TrafficSnapshotUpdate) SetNodeName(v string) *TrafficSnapshotUpdate {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *TrafficSnapshotUpdate) SetNillableNodeName(v *string) *TrafficSnapshotUpdate {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// ClearNodeName clears the value of the "node_name" field.
func (_u *TrafficSnapshotUpdate) ClearNodeName() *TrafficSnapshotUpdate {
	_u.mutation.ClearNodeName()
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *TrafficSnapshotUpdate) SetBytes(v int64) *TrafficSnapshotUpdate {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *TrafficSnapshotUpdate) SetNillableBytes(v *int64) *TrafficSnapshotUpdate {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *TrafficSnapshotUpdate) AddBytes(v int64) *TrafficSnapshotUpdate {
	_u.mutation.AddBytes(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TrafficSnapshotUpdate) SetSyncedAt(v time.Time) *TrafficSnapshotUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TrafficSnapshotUpdate) SetNillableSyncedAt(v *time.Time) *TrafficSnapshotUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the TrafficSnapshotMutation object of the builder.
func (_u *TrafficSnapshotUpdate) Mutation() *TrafficSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrafficSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrafficSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TrafficSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(trafficsnapshot.Table, trafficsnapshot.Columns, sqlgraph.NewFieldSpec(trafficsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(trafficsnapshot.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeUUID(); ok {
		_spec.SetField(trafficsnapshot.FieldNodeUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(trafficsnapshot.FieldNodeName, field.TypeString, value)
	}
	if _u.mutation.NodeNameCleared() {
		_spec.ClearField(trafficsnapshot.FieldNodeName, field.TypeString)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(trafficsnapshot.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(trafficsnapshot.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(trafficsnapshot.FieldSyncedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrafficSnapshotUpdateOne is the builder for updating a single TrafficSnapshot entity.
type TrafficSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrafficSnapshotMutation
}

// SetDate sets the "date" field.
func (_u *TrafficSnapshotUpdateOne) SetDate(v string) *TrafficSnapshotUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TrafficSnapshotUpdateOne) SetNillableDate(v *string) *TrafficSnapshotUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetNodeUUID sets the "node_uuid" field.
func (_u *TrafficSnapshotUpdateOne) SetNodeUUID(v string) *TrafficSnapshotUpdateOne {
	_u.mutation.SetNodeUUID(v)
	return _u
}

// SetNillableNodeUUID sets the "node_uuid" field if the given value is not nil.
func (_u *TrafficSnapshotUpdateOne) SetNillableNodeUUID(v *string) *TrafficSnapshotUpdateOne {
	if v != nil {
		_u.SetNodeUUID(*v)
	}
	return _u
}

// SetNodeName sets the "node_name" field.
func (_u *TrafficSnapshotUpdateOne) SetNodeName(v string) *TrafficSnapshotUpdateOne {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *TrafficSnapshotUpdateOne) SetNillableNodeName(v *string) *TrafficSnapshotUpdateOne {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// ClearNodeName clears the value of the "node_name" field.
func (_u *TrafficSnapshotUpdateOne) ClearNodeName() *TrafficSnapshotUpdateOne {
	_u.mutation.ClearNodeName()
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *TrafficSnapshotUpdateOne) SetBytes(v int64) *TrafficSnapshotUpdateOne {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *TrafficSnapshotUpdateOne) SetNillableBytes(v *int64) *TrafficSnapshotUpdateOne {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *TrafficSnapshotUpdateOne) AddBytes(v int64) *TrafficSnapshotUpdateOne {
	_u.mutation.AddBytes(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TrafficSnapshotUpdateOne) SetSyncedAt(v time.Time) *TrafficSnapshotUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TrafficSnapshotUpdateOne) SetNillableSyncedAt(v *time.Time) *TrafficSnapshotUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the TrafficSnapshotMutation object of the builder.
func (_u *TrafficSnapshotUpdateOne) Mutation() *TrafficSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the TrafficSnapshotUpdate builder.
func (_u *TrafficSnapshotUpdateOne) Where(ps ...predicate.TrafficSnapshot) *TrafficSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrafficSnapshotUpdateOne) Select(field string, fields ...string) *TrafficSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TrafficSnapshot entity.
func (_u *TrafficSnapshotUpdateOne) Save(ctx context.Context) (*TrafficSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficSnapshotUpdateOne) SaveX(ctx context.Context) *TrafficSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrafficSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TrafficSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *TrafficSnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(trafficsnapshot.Table, trafficsnapshot.Columns, sqlgraph.NewFieldSpec(trafficsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrafficSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trafficsnapshot.FieldID)
		for _, f := range fields {
			if !trafficsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trafficsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(trafficsnapshot.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeUUID(); ok {
		_spec.SetField(trafficsnapshot.FieldNodeUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(trafficsnapshot.FieldNodeName, field.TypeString, value)
	}
	if _u.mutation.NodeNameCleared() {
		_spec.ClearField(trafficsnapshot.FieldNodeName, field.TypeString)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(trafficsnapshot.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(trafficsnapshot.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(trafficsnapshot.FieldSyncedAt, field.TypeTime, value)
	}
	_node = &TrafficSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
