// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"vpn-control/ent/trafficsnapshot"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TrafficSnapshot is the model entity for the TrafficSnapshot schema.
type TrafficSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date string `json:"date,omitempty"`
	// NodeUUID holds the value of the "node_uuid" field.
	NodeUUID string `json:"node_uuid,omitempty"`
	// NodeName holds the value of the "node_name" field.
	NodeName string `json:"node_name,omitempty"`
	// Bytes holds the value of the "bytes" field.
	Bytes int64 `json:"bytes,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt     time.Time `json:"synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrafficSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trafficsnapshot.FieldID, trafficsnapshot.FieldBytes:
			values[i] = new(sql.NullInt64)
		case trafficsnapshot.FieldDate, trafficsnapshot.FieldNodeUUID, trafficsnapshot.FieldNodeName:
			values[i] = new(sql.NullString)
		case trafficsnapshot.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrafficSnapshot fields.
func (_m *TrafficSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trafficsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case trafficsnapshot.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.String
			}
		case trafficsnapshot.FieldNodeUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_uuid", values[i])
			} else if value.Valid {
				_m.NodeUUID = value.String
			}
		case trafficsnapshot.FieldNodeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_name", values[i])
			} else if value.Valid {
				_m.NodeName = value.String
			}
		case trafficsnapshot.FieldBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes", values[i])
			} else if value.Valid {
				_m.Bytes = value.Int64
			}
		case trafficsnapshot.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrafficSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *TrafficSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TrafficSnapshot.
// Note that you need to call TrafficSnapshot.Unwrap() before calling this method if this TrafficSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TrafficSnapshot) Update() *TrafficSnapshotUpdateOne {
	return NewTrafficSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TrafficSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TrafficSnapshot) Unwrap() *TrafficSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrafficSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TrafficSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("TrafficSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date)
	builder.WriteString(", ")
	builder.WriteString("node_uuid=")
	builder.WriteString(_m.NodeUUID)
	builder.WriteString(", ")
	builder.WriteString("node_name=")
	builder.WriteString(_m.NodeName)
	builder.WriteString(", ")
	builder.WriteString("bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Bytes))
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrafficSnapshots is a parsable slice of TrafficSnapshot.
type TrafficSnapshots []*TrafficSnapshot
