// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Addon is the predicate function for addon builders.
type Addon func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Expense is the predicate function for expense builders.
type Expense func(*sql.Selector)

// ExpenseItem is the predicate function for expenseitem builders.
type ExpenseItem func(*sql.Selector)

// Extension is the predicate function for extension builders.
type Extension func(*sql.Selector)

// FxRate is the predicate function for fxrate builders.
type FxRate func(*sql.Selector)

// LedgerEntry is the predicate function for ledgerentry builders.
type LedgerEntry func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// ReferralAccrual is the predicate function for referralaccrual builders.
type ReferralAccrual func(*sql.Selector)

// RwUser is the predicate function for rwuser builders.
type RwUser func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// SubscriptionAddon is the predicate function for subscriptionaddon builders.
type SubscriptionAddon func(*sql.Selector)

// Tariff is the predicate function for tariff builders.
type Tariff func(*sql.Selector)

// TariffPeriod is the predicate function for tariffperiod builders.
type TariffPeriod func(*sql.Selector)

// TrafficSnapshot is the predicate function for trafficsnapshot builders.
type TrafficSnapshot func(*sql.Selector)
